// ============================================
// DECKS
// ============================================
// A deck is a named list of words, not a schedule of its own.
//
// The same word belongs to its lesson deck, a frequency band and a topic at
// once. Giving each deck its own schedule would mean meeting that word three
// times in a day and would make its SM-2 interval meaningless, so there is
// still exactly one card per word — engine/srs.js owns it — and a deck is a
// way of choosing which of those cards to study.
//
// Parlour Decks come from content/<lang>/decks/decks.json, generated by
// build-manifest.py out of the vocabulary files, so a deck cannot drift from
// the lesson it describes. They are read-only.
//
// My Decks are the opposite: personal, named collections the learner builds
// themselves, stored client-side and never touching content/. A word can sit
// in any number of them. Removing a word from one, or deleting a deck
// entirely, only ever edits membership — the word's SRS card (if it has one)
// is untouched, because decks organise cards and cards own memory.

const Decks = (function () {
    'use strict';

    const KIND_ORDER = ['lesson', 'topic', 'frequency'];
    const KIND_LABEL = {
        lesson: 'Unit decks',
        topic: 'Topic decks',
        frequency: 'Frequency decks'
    };
    const KIND_BLURB = {
        lesson: 'The words each unit teaches.',
        topic: 'Everything the course says about one subject.',
        get frequency() {
            const lang = (typeof Lang !== 'undefined') ? Lang.name() : 'Spanish';
            return `The most common words in ${lang}, in order. Not all are taught by the course.`;
        }
    };

    let catalogue = null;      // decks.json, once fetched
    let wordLessonIndex = null; // word-lesson-index.json's byLemma map, once fetched
    let myDecks = [];          // custom, learner-owned decks
    let openDeck = null;       // deck id being viewed, or null for the index
    let draft = null;          // deck under construction/edit in the editor, or null
    let activeSection = 'mine'; // 'mine' or 'parlour' — which top-level tab is showing
    let sortOrder = 'natural'; // 'natural' | 'alphabetical' — how the open deck's word list is displayed. Shuffling is a per-mode concern (Match/Learn already randomize their own round), never something that reorders the list itself.
    let studyMode = null;      // null | 'match' | 'learn' — which study mode (if any) is open over the current deck

    // ----------------------------------------
    // DATA — Parlour Decks (read-only catalogue)
    // ----------------------------------------
    async function load() {
        loadMyDecks();
        // Needed for withArticle() below — without it, article() finds no
        // gender data and every card silently falls back to the bare lemma.
        if (typeof Lexicon !== 'undefined') await Lexicon.load();

        // Tier 2 cross-link data (which lesson taught a word, if any) —
        // Content.json() caches by path itself, so calling this on every
        // load() is cheap after the first; not folded into the
        // catalogue-already-loaded early return below so it still resolves
        // even if catalogue was somehow set without going through here.
        if (!wordLessonIndex && typeof Content !== 'undefined') {
            try {
                wordLessonIndex = await Content.json(Lang.content('indexes/word-lesson-index.json'));
            } catch (error) {
                wordLessonIndex = { byLemma: {} };
            }
        }

        if (catalogue) return catalogue;
        try {
            const res = await fetch(Lang.content('decks/decks.json'));
            catalogue = res.ok ? await res.json() : { decks: [] };
        } catch (error) {
            console.warn('Decks: no deck index for this course.', error);
            catalogue = { decks: [] };
        }
        return catalogue;
    }

    function cardFor(lemma) {
        return srsDeck.find(card => card.spanish === lemma);
    }

    // decks.json stores each word once in a shared table and each deck refers
    // to it by lemma, so a word belonging to a lesson, a topic and a frequency
    // band is not written out three times. A My Deck carries its own words
    // directly, since it has no shared table to refer into.
    // Every deck view (My Deck, custom decks, Parlour catalogue decks) reads
    // its word list through here, which makes this the one place to shorten
    // a translation for display — see Lexicon.shortGloss()'s own comment for
    // why: a card wants a translation, not a dictionary entry. Returns a
    // fresh array rather than mutating deck.words in place, since that's the
    // learner's actual saved data.
    function wordsOf(deck) {
        if (deck.words) {
            return deck.words.map(w => Object.assign({}, w, { translation: Lexicon.shortGloss(w.translation) }));
        }
        const table = (catalogue && catalogue.words) || {};
        return (deck.lemmas || []).map(lemma => {
            const entry = table[lemma] || {};
            return { lemma: lemma, translation: Lexicon.shortGloss(entry.en || ''), pos: entry.pos || 'unknown' };
        });
    }

    // A deck's standing: how much of it you have taken on, and how much of
    // that is due. Counted rather than stored, so adding a card anywhere in
    // the app is reflected everywhere without bookkeeping.
    function statusOf(deck) {
        let inDeck = 0, due = 0, mastered = 0, eligible = 0;
        const now = new Date();
        const words = wordsOf(deck);

        words.forEach(word => {
            // A graduated/known word is outside review standing entirely —
            // it has no card on purpose (engine/srs.js keeps known and
            // reviewing mutually exclusive), and isn't "missing" one either,
            // so it must never count toward `missing`/`ready` below or
            // reviewDeck() would treat it as never-added and hand it a
            // fresh card, silently un-graduating it the moment someone
            // clicks Review on a deck (very possibly "All my words" itself,
            // now that My Dictionary lives inside it) that happens to
            // contain it.
            if (word.known || (typeof isKnown === 'function' && isKnown(word.lemma))) return;
            eligible++;
            const card = cardFor(word.lemma);
            if (!card) return;
            inDeck++;
            if ((card.reviews || 0) >= 3) mastered++;
            if (!card.nextReview || new Date(card.nextReview) <= now) due++;
        });

        const missing = eligible - inDeck;
        return {
            total: words.length,
            inDeck: inDeck,
            due: due,
            mastered: mastered,
            missing: missing,
            // What "Review this deck" will actually cover: already-due cards
            // PLUS every word with no card yet — reviewDeck() creates those
            // on the spot (a fresh card is always immediately due), so a
            // learner never has to visit a separate "add to review" step
            // before this count/button becomes real. Known words are
            // excluded above, so they never inflate this.
            ready: due + missing
        };
    }

    // My Deck is every word the learner has taken on, whatever put it there
    // and whether it's still actively cycling through review or has already
    // graduated out — known words carry `known: true` so detailHtml() can
    // tell the two apart without a card lookup (a known word has none).
    // This is the honest total: the other decks are windows onto the same
    // pile, and My Dictionary is a state within this one rather than a
    // separate destination (2026-08-27) — known and reviewing stay
    // mutually exclusive underneath (engine/srs.js), just no longer split
    // across two screens.
    function myDeck() {
        const reviewing = srsDeck.map(card => ({
            lemma: card.spanish,
            translation: card.english,
            pos: card.type,
            source: card.source
        }));
        const known = (typeof knownWords !== 'undefined' ? knownWords : []).map(w => ({
            lemma: w.spanish,
            translation: w.english,
            pos: w.type,
            source: w.source,
            known: true
        }));
        return {
            id: 'mine',
            kind: 'mine',
            name: 'All my words',
            words: reviewing.concat(known)
        };
    }

    function byId(id) {
        if (id === 'mine') return myDeck();
        const custom = myDecks.find(deck => deck.id === id);
        if (custom) return custom;
        return (catalogue.decks || []).find(deck => deck.id === id) || null;
    }

    // ----------------------------------------
    // DATA — My Decks (personal, editable collections)
    // ----------------------------------------
    function myDecksKey() {
        return Lang.key('myDecks');
    }

    function loadMyDecks() {
        try {
            const saved = localStorage.getItem(myDecksKey());
            myDecks = saved ? JSON.parse(saved) : [];
        } catch (error) {
            console.warn('Decks: could not read saved My Decks.', error);
            myDecks = [];
        }
    }

    function saveMyDecks() {
        try {
            localStorage.setItem(myDecksKey(), JSON.stringify(myDecks));
        } catch (error) {
            console.warn('Decks: could not save My Decks.', error);
        }
    }

    function genId() {
        return 'custom-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
    }

    function listMyDecks() {
        return myDecks.slice().sort((a, b) => a.name.localeCompare(b.name));
    }

    // Every lemma sitting in any My Deck, regardless of which one — used by
    // the Library's text analysis to flag "already in your decks" without
    // caring which deck it's in.
    function allMyDeckLemmas() {
        const set = new Set();
        myDecks.forEach(d => d.words.forEach(w => set.add(w.lemma)));
        return set;
    }

    // Adds a word to a stored deck (not the editor draft — see addWordToDraft
    // for that). Used by the "Add to deck" picker, which writes straight
    // through since there is no surrounding form to save. Resolving a
    // manually-typed word to the canonical lexicon entry, where possible,
    // keeps a My Deck from drifting into its own private vocabulary.
    function addWordToDeck(deckId, lemma, translation, pos) {
        const deck = myDecks.find(d => d.id === deckId);
        if (!deck) return false;
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean || deck.words.some(w => w.lemma === clean)) return false;

        const dictEntry = Lexicon.define(clean);
        const finalTranslation = translation || (dictEntry && dictEntry.en) || '';
        const finalPos = pos || (dictEntry && dictEntry.type) || '';

        deck.words.push({ lemma: clean, translation: finalTranslation, pos: finalPos });
        saveMyDecks();

        // Adding a word now activates it for review on the spot, the same
        // way reviewDeck() already does for a whole deck at once — before
        // this (2026-09-02), "Add to a deck" looked like it captured the
        // word but didn't actually make it reviewable, due, or counted
        // anywhere (Home's Review door, Journey's stats) until the deck
        // was separately opened and reviewed later. Skipped for a word
        // that's already graduated, same guard reviewDeck() itself uses,
        // so this can't silently un-graduate a known word.
        const alreadyGraduated = typeof isKnown === 'function' && isKnown(clean);
        if (!cardFor(clean) && !alreadyGraduated) {
            srsDeck.push(Object.assign({
                spanish: clean,
                english: finalTranslation || 'unknown',
                type: finalPos || 'unknown',
                source: deckId,
                added: new Date().toISOString()
            }, newCardSchedule()));
            saveDeck();
        }

        return true;
    }

    function removeWordFromDeck(deckId, lemma) {
        const deck = myDecks.find(d => d.id === deckId);
        if (!deck) return;
        deck.words = deck.words.filter(w => w.lemma !== lemma);
        saveMyDecks();
    }

    // Deleting a deck only removes the membership list. The words themselves,
    // and any SRS cards built from them, are untouched — they may still
    // belong to other decks, or to nothing at all, same as any other word.
    function deleteMyDeck(deckId) {
        myDecks = myDecks.filter(d => d.id !== deckId);
        saveMyDecks();
        if (openDeck === deckId) openDeck = null;
    }

    // ----------------------------------------
    // ACTIONS — review
    // ----------------------------------------
    // Reviewing a deck IS what turns its membership into SRS activation —
    // there used to be a separate "Add N to review" step required before
    // Review would do anything, which was exactly the two-clicks-for-one-
    // action friction the whole flow got simplified to remove (2026-08-27).
    // Any word here with no card yet gets a fresh one on the spot; a fresh
    // card is always immediately due, so it's included in this session
    // without a separate visit first. No daily cap here either, by the
    // same 2026-08-27 decision: the cap in engine/xp.js exists to stop the
    // Reader's incidental, one-word-at-a-time "+Add to SRS Deck" from
    // burying a learner mid-reading — a deliberate whole-deck review is a
    // different act with its own built-in judgment call, and doesn't call
    // canAddNewWord()/recordNewWord() at all, so it neither gets blocked by
    // that cap nor eats into it for the Reader's sake either.
    function reviewDeck(id) {
        const deck = id === 'all' ? null : byId(id);
        if (deck) {
            wordsOf(deck).forEach(word => {
                if (cardFor(word.lemma)) return;
                // A graduated word has no card on purpose — creating one
                // here would silently un-graduate it (see statusOf()'s
                // matching guard, above).
                if (word.known || (typeof isKnown === 'function' && isKnown(word.lemma))) return;
                srsDeck.push(Object.assign({
                    spanish: word.lemma,
                    english: word.translation || 'unknown',
                    type: word.pos || 'unknown',
                    source: deck.id,
                    added: new Date().toISOString()
                }, newCardSchedule()));
            });
            saveDeck();
        }
        startReviewSession(deck ? wordsOf(deck).map(w => w.lemma) : null,
                           deck ? deck.name : 'All decks');
    }

    // ----------------------------------------
    // EDITOR — create / edit a My Deck
    // ----------------------------------------
    // The editor works on a draft copy so "Cancel" is honest — nothing is
    // written to storage until Save. Word add/remove happen against the
    // draft too, for the same reason: they are part of the same commit as
    // the name and description, not separate actions.
    function openCreateDeck() {
        draft = { id: null, name: '', description: '', words: [] };
        Lexicon.load();     // warm the dictionary before the learner starts typing
        render();
    }

    function openEditDeck(id) {
        const deck = myDecks.find(d => d.id === id);
        if (!deck) return;
        draft = {
            id: deck.id,
            name: deck.name,
            description: deck.description || '',
            words: deck.words.slice()
        };
        Lexicon.load();
        render();
    }

    function closeEditor() {
        draft = null;
        render();
    }

    function saveDraft() {
        const name = (draft.name || '').trim();
        if (!name) {
            alert('Give the deck a name first.');
            return;
        }
        const description = (draft.description || '').trim();

        if (draft.id) {
            const deck = myDecks.find(d => d.id === draft.id);
            deck.name = name;
            deck.description = description;
            deck.words = draft.words;
        } else {
            myDecks.push({
                id: genId(), kind: 'custom', name, description,
                created: new Date().toISOString(),
                words: draft.words
            });
        }
        saveMyDecks();
        draft = null;
        render();
    }

    function deleteDraft() {
        if (!draft.id) return;
        if (!confirm(`Delete "${draft.name}"? Its words keep their place in your review deck.`)) return;
        deleteMyDeck(draft.id);
        draft = null;
        render();
    }

    function addWordToDraft(lemma, translation, pos) {
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean || draft.words.some(w => w.lemma === clean)) return;
        draft.words.push({ lemma: clean, translation: translation || '', pos: pos || '' });
        render();
    }

    function addManualWordToDraft(raw) {
        const clean = String(raw || '').toLowerCase().trim();
        if (!clean) return;
        if (draft.words.some(w => w.lemma === clean)) return;
        const known = Lexicon.define(clean);
        if (known) {
            addWordToDraft(clean, Lexicon.shortGloss(known.en), known.type);
            return;
        }
        const translation = prompt(`"${clean}" isn't in the Parlour dictionary yet. What does it mean?`);
        if (translation === null) return;
        addWordToDraft(clean, translation.trim(), '');
    }

    function removeWordFromDraft(lemma) {
        draft.words = draft.words.filter(w => w.lemma !== lemma);
        render();
    }

    // Debounced so a fast typist doesn't run a full-dictionary scan on every
    // keystroke. Rendered straight into the results container rather than
    // through the normal render() path, so the search field itself never
    // loses focus while the learner is typing.
    let searchTimer = null;
    function onEditorSearch(query) {
        clearTimeout(searchTimer);
        searchTimer = setTimeout(() => renderEditorResults(query), 150);
    }

    async function renderEditorResults(query) {
        const host = document.getElementById('dk-editor-results');
        if (!host) return;
        const q = (query || '').trim();
        if (!q) { host.innerHTML = ''; return; }

        if (!Lexicon.isLoaded()) {
            host.innerHTML = '<p class="dk-picker-loading">Loading dictionary…</p>';
            await Lexicon.load();
            const current = document.getElementById('dk-editor-search');
            if (!current || current.value.trim() !== q) return;
        }

        // Shortened here, once — feeds both the preview text and the
        // data-editor-add-en attribute the click handler below reads to
        // build the draft word, so what's added matches what was shown.
        const results = Lexicon.search(q, 8)
            .map(r => Object.assign({}, r, { translation: Lexicon.shortGloss(r.translation) }));
        const already = new Set(draft.words.map(w => w.lemma));

        host.innerHTML = `
            <ul class="dk-picker-results">
                ${results.map(r => `
                    <li>
                        <button class="dk-picker-result" data-editor-add="${esc(r.lemma)}"
                            data-editor-add-en="${esc(r.translation || '')}"
                            data-editor-add-pos="${esc(r.pos || '')}"
                            ${already.has(r.lemma) ? 'disabled' : ''}>
                            <span class="dk-picker-result-es">${esc(withArticle(r.lemma))}</span>
                            <span class="dk-picker-result-en">${esc(r.translation || '—')}</span>
                            ${already.has(r.lemma) ? '<span class="dk-picker-result-added">✓</span>' : ''}
                        </button>
                    </li>
                `).join('')}
            </ul>
            <button class="dk-picker-manual" data-editor-add-manual="${esc(q)}">
                Not here? Add "${esc(q)}" yourself
            </button>
        `;

        host.querySelectorAll('[data-editor-add]').forEach(el => {
            el.onclick = function () {
                addWordToDraft(
                    el.getAttribute('data-editor-add'),
                    el.getAttribute('data-editor-add-en'),
                    el.getAttribute('data-editor-add-pos')
                );
                const search = document.getElementById('dk-editor-search');
                if (search) { search.value = ''; search.focus(); }
                host.innerHTML = '';
            };
        });
        host.querySelectorAll('[data-editor-add-manual]').forEach(el => {
            el.onclick = function () {
                addManualWordToDraft(el.getAttribute('data-editor-add-manual'));
                const search = document.getElementById('dk-editor-search');
                if (search) { search.value = ''; search.focus(); }
                host.innerHTML = '';
            };
        });
    }

    function editorHtml() {
        const isNew = !draft.id;
        const rows = draft.words.map(w => `
            <li class="dk-word">
                <span class="dk-word-es">${esc(withArticle(w.lemma))}</span>
                <span class="dk-word-en">${esc(Lexicon.shortGloss(w.translation) || '—')}</span>
                <button class="dk-word-remove" data-editor-remove="${esc(w.lemma)}"
                    aria-label="Remove ${esc(w.lemma)}">×</button>
            </li>
        `).join('');

        return `
            <button class="dk-back" data-editor-cancel="1">← My Decks</button>
            <div class="dk-editor">
                <h3 class="dk-editor-title">${isNew ? 'Create a deck' : 'Edit deck'}</h3>

                <label class="dk-editor-label" for="dk-editor-name">Name</label>
                <input id="dk-editor-name" class="dk-editor-input" type="text"
                    placeholder="e.g. Travel essentials" value="${esc(draft.name)}" maxlength="60">

                <label class="dk-editor-label" for="dk-editor-desc">Description (optional)</label>
                <textarea id="dk-editor-desc" class="dk-editor-input dk-editor-textarea"
                    placeholder="What this deck is for" maxlength="200">${esc(draft.description)}</textarea>

                <label class="dk-editor-label" for="dk-editor-search">Add vocabulary</label>
                <input id="dk-editor-search" class="dk-editor-input" type="text"
                    placeholder="Search in ${Lang.name()} or English…" autocomplete="off">
                <div id="dk-editor-results" class="dk-picker-panel"></div>

                <ul class="dk-words dk-editor-words">
                    ${rows || '<li class="dk-empty">No words yet. Search above to add some.</li>'}
                </ul>

                <div class="dk-actions dk-editor-actions">
                    <button class="btn-primary" data-editor-save="1">Save deck</button>
                    ${!isNew ? '<button class="dk-danger" data-editor-delete="1">Delete deck</button>' : ''}
                </div>
            </div>
        `;
    }

    function wireEditor(host) {
        const name = document.getElementById('dk-editor-name');
        const desc = document.getElementById('dk-editor-desc');
        const search = document.getElementById('dk-editor-search');
        if (name) name.oninput = e => { draft.name = e.target.value; };
        if (desc) desc.oninput = e => { draft.description = e.target.value; };
        if (search) search.oninput = e => onEditorSearch(e.target.value);

        host.querySelectorAll('[data-editor-remove]').forEach(el => {
            el.onclick = function () { removeWordFromDraft(el.getAttribute('data-editor-remove')); };
        });
        host.querySelectorAll('[data-editor-cancel]').forEach(el => { el.onclick = closeEditor; });
        host.querySelectorAll('[data-editor-save]').forEach(el => { el.onclick = saveDraft; });
        host.querySelectorAll('[data-editor-delete]').forEach(el => { el.onclick = deleteDraft; });
    }

    // ----------------------------------------
    // PICKER — "Add to deck" from anywhere a word appears
    // ----------------------------------------
    // A standalone overlay, independent of the Decks tab's own render cycle,
    // so it can be opened from the reader (or any future word-tapping
    // surface) without navigating away from what the learner was doing.
    // Adding a word here is membership only: it does not touch the SRS
    // schedule, so a learner can stash 50 words in a deck without being
    // asked to learn 50 words today.
    function ensurePicker() {
        let el = document.getElementById('deck-picker');
        if (el) return el;
        el = document.createElement('div');
        el.id = 'deck-picker';
        document.body.appendChild(el);
        return el;
    }

    function closePicker() {
        const el = document.getElementById('deck-picker');
        if (el) el.innerHTML = '';
    }

    function pickerListHtml(isDone) {
        const decks = listMyDecks();
        if (!decks.length) {
            return '<p class="dk-empty">No decks yet — create one below.</p>';
        }
        return `
            <ul class="dk-picker-list">
                ${decks.map(d => {
                    const done = isDone(d);
                    return `
                        <li>
                            <button class="dk-picker-deck" data-picker-add="${esc(d.id)}" ${done ? 'disabled' : ''}>
                                <span>${esc(d.name)}</span>
                                <span class="dk-picker-deck-count">${done ? '✓ added' : d.words.length + ' words'}</span>
                            </button>
                        </li>
                    `;
                }).join('')}
            </ul>
        `;
    }

    // Shared shell for both "Add to deck" pickers below — one word from the
    // reader, or a batch from the Library's vocabulary selection. `isDone`
    // decides when a deck row shows as already satisfied; `onPick`/`onCreate`
    // do the actual adding for a chosen (or newly created) deck.
    function openPicker(titleHtml, isDone, onPick, onCreate) {
        loadMyDecks();
        if (typeof Lexicon !== 'undefined') Lexicon.load();

        const host = ensurePicker();
        host.innerHTML = `
            <div class="wp-overlay" id="deck-picker-overlay">
                <div class="wp-sheet dk-picker-sheet">
                    <div class="wp-header">
                        <h2 class="wp-word">${titleHtml}</h2>
                        <button class="wp-close" data-picker-close="1" aria-label="Close">×</button>
                    </div>
                    <div id="deck-picker-list">${pickerListHtml(isDone)}</div>
                    <div class="dk-picker-create">
                        <input id="deck-picker-new-name" class="dk-editor-input" type="text"
                            placeholder="New deck name" maxlength="60">
                        <button class="dk-secondary" data-picker-create="1">+ Create &amp; add</button>
                    </div>
                </div>
            </div>
        `;

        function refreshList() {
            const list = document.getElementById('deck-picker-list');
            if (list) list.innerHTML = pickerListHtml(isDone);
            wireList();
        }

        function wireList() {
            host.querySelectorAll('[data-picker-add]').forEach(el => {
                el.onclick = function () {
                    onPick(el.getAttribute('data-picker-add'));
                    refreshList();
                };
            });
        }

        host.querySelectorAll('[data-picker-close]').forEach(el => { el.onclick = closePicker; });
        const overlay = document.getElementById('deck-picker-overlay');
        if (overlay) overlay.onclick = function (e) { if (e.target === overlay) closePicker(); };

        host.querySelectorAll('[data-picker-create]').forEach(el => {
            el.onclick = function () {
                const input = document.getElementById('deck-picker-new-name');
                const name = (input.value || '').trim();
                if (!name) { input.focus(); return; }
                myDecks.push({
                    id: genId(), kind: 'custom', name, description: '',
                    created: new Date().toISOString(), words: []
                });
                saveMyDecks();
                onCreate(myDecks[myDecks.length - 1].id);
                input.value = '';
                refreshList();
            };
        });

        wireList();
    }

    function openAddToDeckPicker(lemma, translation, pos) {
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean) return;
        const add = deckId => addWordToDeck(deckId, clean, translation, pos);
        openPicker(
            `Add "${esc(withArticle(clean))}" to a deck`,
            deck => deck.words.some(w => w.lemma === clean),
            add, add
        );
    }

    // Same overlay, for several words at once — the Library's vocabulary
    // selection view (see engine/library.js) sends every checked word to one
    // deck in a single action rather than one popup per word.
    function openBulkAddPicker(items) {
        const list = (items || [])
            .filter(it => it && it.lemma)
            .map(it => Object.assign({}, it, { lemma: String(it.lemma).toLowerCase().trim() }));
        if (!list.length) return;

        const addAll = deckId => { list.forEach(it => addWordToDeck(deckId, it.lemma, it.translation, it.pos)); };
        openPicker(
            `Add ${list.length} ${list.length === 1 ? 'word' : 'words'} to a deck`,
            deck => list.every(it => deck.words.some(w => w.lemma === it.lemma)),
            addAll, addAll
        );
    }

    // ----------------------------------------
    // RENDER
    // ----------------------------------------
    function esc(value) {
        return (typeof UI !== 'undefined' && UI.escape)
            ? UI.escape(value) : String(value == null ? '' : value);
    }

    // "gato" -> "el gato". Lexicon owns the formatting (Library uses the same
    // one); this is a live lookup rather than anything stored on the word,
    // since the dictionary may not have been loaded yet when the word was
    // first saved.
    function withArticle(lemma) {
        return (typeof Lexicon !== 'undefined') ? Lexicon.withArticle(lemma) : lemma;
    }

    function deckCard(deck) {
        const s = statusOf(deck);
        const percent = s.total ? Math.round((s.inDeck / s.total) * 100) : 0;
        const preview = wordsOf(deck).slice(0, 5).map(w => withArticle(w.lemma)).join(' · ');

        return `
            <button class="dk-card" data-open-deck="${esc(deck.id)}">
                <span class="dk-card-top">
                    ${deck.label ? `<span class="dk-num">${esc(deck.label)}</span>` : ''}
                    <span class="dk-name">${esc(deck.name)}</span>
                    ${s.due ? `<span class="dk-due">${s.due}</span>` : ''}
                </span>
                <span class="dk-preview">${esc(preview) || 'No words yet'}</span>
                <span class="dk-meter"><span class="dk-fill" style="width:${percent}%"></span></span>
                <span class="dk-meta">
                    <span>${s.total} ${s.total === 1 ? 'word' : 'words'}</span>
                    <span>${s.inDeck ? s.inDeck + ' in your deck' : 'none added yet'}</span>
                </span>
            </button>
        `;
    }

    // My Decks and Parlour Decks are tabs on one subnav — same lt-subnav
    // component the Library uses for Parlour/Saved/My Texts — rather than
    // two stacked lists, so a learner isn't scrolling past a wall of My
    // Decks to reach the course's 300-odd curated ones, or vice versa.
    function myDecksSectionHtml() {
        const decks = listMyDecks();
        return `
            <div class="lt-index-head">
                <p class="dk-group-blurb">Your own collections. Add any word, from anywhere in Parlour.</p>
                <button class="dk-secondary dk-create-btn" data-create-deck="1">+ Create deck</button>
            </div>
            ${decks.length
                ? `<div class="dk-grid">${decks.map(deckCard).join('')}</div>`
                : '<p class="dk-empty">No decks yet. Create one to start collecting words.</p>'}
        `;
    }

    function parlourDecksSectionHtml() {
        const decks = catalogue.decks || [];
        const groups = KIND_ORDER.map(kind => {
            const group = decks.filter(deck => deck.kind === kind);
            if (!group.length) return '';
            return `
                <section class="dk-group">
                    <button class="dk-group-header" data-group-toggle="${kind}" aria-expanded="false">
                        <span>
                            <span class="dk-group-title">${esc(KIND_LABEL[kind])}</span>
                            <span class="dk-group-count">${group.length}</span>
                        </span>
                        <span class="dk-group-arrow" id="dk-group-arrow-${kind}" aria-hidden="true">▶</span>
                    </button>
                    <div class="dk-group-body hidden" id="dk-group-body-${kind}">
                        <p class="dk-group-blurb">${KIND_BLURB[kind]}</p>
                        <div class="dk-grid">${group.map(deckCard).join('')}</div>
                    </div>
                </section>
            `;
        }).join('');

        return `
            <p class="dk-group-blurb">Curated by the course. Browse and review them, or add
                their words to a deck of your own.</p>
            ${groups || '<p class="dk-empty">No decks for this course yet.</p>'}
        `;
    }

    function indexHtml() {
        const mine = myDeck();
        const mineStatus = statusOf(mine);
        const myDeckCount = listMyDecks().length;
        const parlourCount = (catalogue.decks || []).length;
        const knownCount = (typeof knownWords !== 'undefined') ? knownWords.length : 0;
        const reviewedToday = (typeof getDay === 'function' && typeof getTodayString === 'function')
            ? getDay(getTodayString()).reviewsDone : 0;

        return `
            <div class="dk-top">
                <div class="dk-stats-row">
                    <div class="dk-stat">
                        <p class="dk-stat-num">${mineStatus.due}</p>
                        <p class="dk-stat-label">waiting to review</p>
                    </div>
                    <div class="dk-stat">
                        <p class="dk-stat-num">${reviewedToday}</p>
                        <p class="dk-stat-label">reviewed today</p>
                    </div>
                    <div class="dk-stat">
                        <p class="dk-stat-num">${knownCount}</p>
                        <p class="dk-stat-label">known</p>
                    </div>
                </div>
                <div class="dk-actions">
                    <button class="btn-primary" data-review-deck="all"
                        ${mineStatus.due ? '' : 'disabled'}>
                        Review all${mineStatus.due ? ` (${mineStatus.due})` : ''}
                    </button>
                    <button data-open-deck="mine" class="dk-secondary">All my words</button>
                </div>
            </div>
            <nav class="lt-subnav" id="dk-subnav">
                <button class="lt-subnav-btn${activeSection === 'mine' ? ' active' : ''}"
                    data-dk-tab="mine">My Decks <span class="dk-group-count">${myDeckCount}</span></button>
                <button class="lt-subnav-btn${activeSection === 'parlour' ? ' active' : ''}"
                    data-dk-tab="parlour">Parlour Decks <span class="dk-group-count">${parlourCount}</span></button>
            </nav>
            ${activeSection === 'parlour' ? parlourDecksSectionHtml() : myDecksSectionHtml()}
        `;
    }

    // The deck's word list in whatever order the learner currently has it
    // displayed in (natural/insertion order, or A-Z) — shared by the deck
    // detail list and by Flashcards' un-shuffled starting order, so opening
    // Flashcards with shuffle off matches what's on screen.
    function orderedWords(deck) {
        const natural = wordsOf(deck);
        return sortOrder === 'alphabetical'
            ? natural.slice().sort((a, b) => withArticle(a.lemma).localeCompare(withArticle(b.lemma)))
            : natural;
    }

    function detailHtml(deck) {
        const s = statusOf(deck);
        const isCustom = deck.kind === 'custom';
        // "All my words" has no membership list of its own to edit — it is
        // just the shared SRS pile — so removing a word here means deleting
        // its card outright, not unlinking it from a deck.
        const removable = deck.id === 'mine';

        // Natural = insertion order for a My Deck, or decks.json's authored
        // order for a Parlour Deck — the order the learner (or the course)
        // actually added the words in, which is the sensible default for a
        // reference list. Sort A-Z is the one alternative offered; shuffling
        // is deliberately NOT a list-ordering option any more — it belongs
        // to Flashcards' own presentation-order toggle, so browsing the list
        // itself always stays predictable.
        const words = orderedWords(deck);

        const rows = words.map(word => {
            const isKnownWord = word.known || (typeof isKnown === 'function' && isKnown(word.lemma));
            const card = cardFor(word.lemma);
            const state = isKnownWord ? 'known'
                : !card ? 'not added'
                : (card.reviews || 0) >= 3 ? 'mastered'
                : (card.reviews || 0) >= 1 ? 'learning'
                : 'new';
            // A known word's row action is "Back to review" rather than the
            // usual delete — it isn't gone, it graduated, and pulling it
            // back into review is the one thing removeFromAllWords() (which
            // deletes review history outright) shouldn't be doing to it.
            const rowAction = !removable ? ''
                : isKnownWord
                    ? `<button class="dk-link-btn dk-word-restore" data-move-to-review="${esc(word.lemma)}">Back to review</button>`
                    : `<button class="dk-word-remove" data-remove-card="${esc(word.lemma)}"
                        aria-label="Remove ${esc(word.lemma)}">×</button>`;

            // Tier 2 cross-link — only shown when the word is actually in
            // word-lesson-index.json (see scripts/build_word_lesson_index.py);
            // a frequency-deck word the curriculum never formally taught
            // just doesn't get a line, rather than a link with nothing
            // honest behind it. Resolved against the already-loaded
            // curriculum data at render time (lessonLabelFor(), engine/
            // lessons.js) rather than cached in the index itself, so a
            // renamed lesson can never leave a stale title here.
            const lessonId = wordLessonIndex && wordLessonIndex.byLemma && wordLessonIndex.byLemma[word.lemma];
            const lessonInfo = lessonId && typeof lessonLabelFor === 'function' ? lessonLabelFor(lessonId) : null;
            const lessonLink = lessonInfo
                ? `<button class="dk-link-btn dk-word-lesson-link" data-open-lesson="${esc(lessonId)}">${esc(lessonInfo.label)}</button>`
                : '';

            return `
                <li class="dk-word dk-word-${state.replace(' ', '-')}">
                    <span class="dk-word-es">${esc(withArticle(word.lemma))}${
                        typeof Speech !== 'undefined' ? Speech.button(word.lemma) : ''}</span>
                    <span class="dk-word-en">${esc(word.translation)}</span>
                    <span class="dk-word-state">${state}</span>
                    ${lessonLink}
                    ${rowAction}
                </li>
            `;
        }).join('');

        return `
            <button class="dk-back" data-close-deck="1">← All decks</button>
            <div class="dk-detail-head">
                <h3>${esc(deck.name)}</h3>
                ${deck.description ? `<p class="dk-detail-desc">${esc(deck.description)}</p>` : ''}
                <p>${s.mastered} mastered${s.total ? ` · ${s.total} ${s.total === 1 ? 'word' : 'words'} total` : ''}</p>

                <!-- Three equal ways to engage with this deck right now — same size,
                     same weight, no one of them "the" primary action the way
                     Review used to visually outrank Match/Learn. Review no
                     longer needs a separate "add to review" step first — it
                     activates any not-yet-added word on the spot (see
                     reviewDeck()) — so its badge is simply "everything this
                     click covers right now", not a status claim about which
                     mode matters more. -->
                <div class="dk-study-row">
                    <button class="dk-study-tab" data-review-deck="${esc(deck.id)}" ${s.ready ? '' : 'disabled'}>
                        <span class="dk-study-tab-label">Review</span>
                        ${s.ready ? `<span class="dk-study-tab-badge">${s.ready}</span>` : ''}
                    </button>
                    ${words.length > 1 ? `<button class="dk-study-tab" data-open-match="1"><span class="dk-study-tab-label">Match</span></button>` : ''}
                    ${words.length ? `<button class="dk-study-tab" data-open-learn="1"><span class="dk-study-tab-label">Learn</span></button>` : ''}
                </div>

                ${isCustom ? `
                    <div class="dk-utility-row">
                        <button class="dk-link-btn" data-edit-deck="${esc(deck.id)}">Edit deck</button>
                    </div>
                ` : ''}

                ${deck.id === 'mine' ? `
                    <div class="dk-dictionary-add">
                        <input type="text" id="dict-add-input" class="lsn-input" placeholder="Mark a word known, e.g. vivir">
                        <button class="dk-secondary" id="dict-add-btn">+ Add</button>
                    </div>
                    <p id="dict-add-feedback" class="dk-meta-line"></p>
                ` : ''}
            </div>
            ${words.length > 1 ? `
                <div class="dk-words-head">
                    <span class="dk-words-count">${words.length} ${words.length === 1 ? 'word' : 'words'}</span>
                    <button class="dk-link-btn" data-toggle-sort="1">
                        ${sortOrder === 'alphabetical' ? 'Sorted A–Z' : 'Added order'}
                    </button>
                </div>
            ` : ''}
            <ul class="dk-words${removable ? ' dk-words-removable' : ''}">${rows || '<li class="dk-empty">No words yet.</li>'}</ul>
        `;
    }

    function addKnownWordByHand() {
        const input = document.getElementById('dict-add-input');
        const feedback = document.getElementById('dict-add-feedback');
        if (!input) return;

        const raw = input.value.trim().toLowerCase();
        if (!raw) return;

        const entry = (typeof Lexicon !== 'undefined') ? Lexicon.define(raw) : null;
        if (!entry) {
            if (feedback) feedback.textContent = `Couldn't find "${raw}" in the dictionary.`;
            return;
        }

        const added = (typeof addKnownWord === 'function') && addKnownWord(raw, Lexicon.shortGloss(entry.en), entry.type, 'manual');
        if (feedback) feedback.textContent = added ? `Added "${raw}."` : `"${raw}" is already known.`;
        input.value = '';
        render();
    }

    // Deleting a word from "All my words" deletes its SRS card — there is
    // nothing else to remove it from. That is different from removing a word
    // from a My Deck, which only ever touches membership; this is the one
    // place in the UI that reaches into the card pile itself, so it asks
    // first.
    function removeFromAllWords(lemma) {
        if (!confirm(`Remove "${lemma}" from your deck? This deletes its review history.`)) return;
        srsDeck = srsDeck.filter(card => card.spanish !== lemma);
        saveDeck();
        render();
    }

    async function render() {
        const host = document.getElementById('decks-root');
        if (!host) return;

        await load();

        if (draft) {
            host.innerHTML = editorHtml();
            wireEditor(host);
            return;
        }

        const deck = openDeck ? byId(openDeck) : null;

        // A study mode is a self-contained module (engine/decks/*.js, same
        // pattern as Workshop's drillers) rendered in place of the deck
        // detail screen — closing it just clears studyMode and re-renders,
        // landing back on the same deck rather than the deck index.
        if (studyMode && deck) {
            if (studyMode === 'match' && typeof DeckMatch !== 'undefined') {
                DeckMatch.render(host, {
                    words: wordsOf(deck),
                    deckId: deck.id,
                    onExit: () => { studyMode = null; render(); }
                });
                return;
            }
            if (studyMode === 'learn' && typeof DeckLearn !== 'undefined') {
                DeckLearn.render(host, {
                    words: wordsOf(deck),
                    onExit: () => { studyMode = null; render(); }
                });
                return;
            }
            studyMode = null; // module missing/unknown — fall through to the deck screen rather than a blank one
        }

        host.innerHTML = deck ? detailHtml(deck) : indexHtml();

        host.querySelectorAll('[data-open-match]').forEach(el => {
            el.onclick = function () { studyMode = 'match'; render(); };
        });
        host.querySelectorAll('[data-open-learn]').forEach(el => {
            el.onclick = function () { studyMode = 'learn'; render(); };
        });
        host.querySelectorAll('[data-group-toggle]').forEach(el => {
            el.onclick = function () {
                const kind = el.getAttribute('data-group-toggle');
                const body = document.getElementById('dk-group-body-' + kind);
                const arrow = document.getElementById('dk-group-arrow-' + kind);
                if (!body) return;
                const nowOpen = body.classList.toggle('hidden') === false;
                el.setAttribute('aria-expanded', String(nowOpen));
                if (arrow) arrow.textContent = nowOpen ? '▼' : '▶';
            };
        });
        host.querySelectorAll('[data-open-deck]').forEach(el => {
            el.onclick = function () { openDeck = el.getAttribute('data-open-deck'); sortOrder = 'natural'; studyMode = null; render(); };
        });
        host.querySelectorAll('[data-close-deck]').forEach(el => {
            el.onclick = function () { openDeck = null; sortOrder = 'natural'; studyMode = null; render(); };
        });
        host.querySelectorAll('[data-toggle-sort]').forEach(el => {
            el.onclick = function () {
                sortOrder = sortOrder === 'alphabetical' ? 'natural' : 'alphabetical';
                render();
            };
        });
        host.querySelectorAll('[data-remove-card]').forEach(el => {
            el.onclick = function () { removeFromAllWords(el.getAttribute('data-remove-card')); };
        });
        host.querySelectorAll('[data-move-to-review]').forEach(el => {
            el.onclick = function () {
                if (typeof moveKnownToReview === 'function') {
                    moveKnownToReview(el.getAttribute('data-move-to-review'));
                }
                render();
            };
        });
        {
            const addBtn = document.getElementById('dict-add-btn');
            if (addBtn) addBtn.onclick = addKnownWordByHand;
            const addInput = document.getElementById('dict-add-input');
            if (addInput) addInput.onkeydown = e => { if (e.key === 'Enter') addKnownWordByHand(); };
        }
        host.querySelectorAll('[data-review-deck]').forEach(el => {
            el.onclick = function () { reviewDeck(el.getAttribute('data-review-deck')); };
        });
        host.querySelectorAll('[data-create-deck]').forEach(el => {
            el.onclick = function () { openCreateDeck(); };
        });
        host.querySelectorAll('[data-dk-tab]').forEach(el => {
            el.onclick = function () { activeSection = el.getAttribute('data-dk-tab'); render(); };
        });
        host.querySelectorAll('[data-edit-deck]').forEach(el => {
            el.onclick = function () { openEditDeck(el.getAttribute('data-edit-deck')); };
        });
        // Tier 2 cross-link: jump straight into the lesson that taught this
        // word, same as the Reader popup's equivalent link.
        host.querySelectorAll('[data-open-lesson]').forEach(el => {
            el.onclick = function (e) {
                e.stopPropagation();
                if (typeof startLesson === 'function') startLesson(el.getAttribute('data-open-lesson'));
            };
        });
    }

    return {
        render, load, statusOf, myDeck, reviewDeck,
        openAddToDeckPicker, openBulkAddPicker, allMyDeckLemmas
    };
})();
