// ============================================
// DECKS
// ============================================
// A deck is a named list of words, not a schedule of its own.
//
// The same word belongs to its lesson deck, a frequency band and a topic at
// once. Giving each deck its own schedule would mean meeting that word three
// times in a day and would make its SM-2 interval meaningless, so there is
// still exactly one card per word — engine/srs.js owns it — and a deck is a
// way of choosing which of those cards to study.
//
// Parlour Decks come from content/<lang>/decks/decks.json, generated by
// build-manifest.py out of the vocabulary files, so a deck cannot drift from
// the lesson it describes. They are read-only.
//
// My Decks are the opposite: personal, named collections the learner builds
// themselves, stored client-side and never touching content/. A word can sit
// in any number of them. Removing a word from one, or deleting a deck
// entirely, only ever edits membership — the word's SRS card (if it has one)
// is untouched, because decks organise cards and cards own memory.

const Decks = (function () {
    'use strict';

    const KIND_ORDER = ['lesson', 'topic', 'frequency'];
    const KIND_LABEL = {
        lesson: 'Lesson decks',
        topic: 'Topic decks',
        frequency: 'Frequency decks'
    };
    const KIND_BLURB = {
        lesson: 'The words each lesson teaches.',
        topic: 'Everything the course says about one subject.',
        get frequency() {
            const lang = (typeof Lang !== 'undefined') ? Lang.name() : 'Spanish';
            return `The most common words in ${lang}, in order. Not all are taught by the course.`;
        }
    };

    let catalogue = null;      // decks.json, once fetched
    let myDecks = [];          // custom, learner-owned decks
    let openDeck = null;       // deck id being viewed, or null for the index
    let draft = null;          // deck under construction/edit in the editor, or null
    let activeSection = 'mine'; // 'mine' or 'parlour' — which top-level tab is showing
    let showDictionary = false; // My Dictionary (known words) view, instead of the index

    // ----------------------------------------
    // DATA — Parlour Decks (read-only catalogue)
    // ----------------------------------------
    async function load() {
        loadMyDecks();
        // Needed for withArticle() below — without it, article() finds no
        // gender data and every card silently falls back to the bare lemma.
        if (typeof Lexicon !== 'undefined') await Lexicon.load();
        if (catalogue) return catalogue;
        try {
            const res = await fetch(Lang.content('decks/decks.json'));
            catalogue = res.ok ? await res.json() : { decks: [] };
        } catch (error) {
            console.warn('Decks: no deck index for this course.', error);
            catalogue = { decks: [] };
        }
        return catalogue;
    }

    function cardFor(lemma) {
        return srsDeck.find(card => card.spanish === lemma);
    }

    // decks.json stores each word once in a shared table and each deck refers
    // to it by lemma, so a word belonging to a lesson, a topic and a frequency
    // band is not written out three times. A My Deck carries its own words
    // directly, since it has no shared table to refer into.
    // Every deck view (My Deck, custom decks, Parlour catalogue decks) reads
    // its word list through here, which makes this the one place to shorten
    // a translation for display — see Lexicon.shortGloss()'s own comment for
    // why: a card wants a translation, not a dictionary entry. Returns a
    // fresh array rather than mutating deck.words in place, since that's the
    // learner's actual saved data.
    function wordsOf(deck) {
        if (deck.words) {
            return deck.words.map(w => Object.assign({}, w, { translation: Lexicon.shortGloss(w.translation) }));
        }
        const table = (catalogue && catalogue.words) || {};
        return (deck.lemmas || []).map(lemma => {
            const entry = table[lemma] || {};
            return { lemma: lemma, translation: Lexicon.shortGloss(entry.en || ''), pos: entry.pos || 'unknown' };
        });
    }

    // A deck's standing: how much of it you have taken on, and how much of
    // that is due. Counted rather than stored, so adding a card anywhere in
    // the app is reflected everywhere without bookkeeping.
    function statusOf(deck) {
        let inDeck = 0, due = 0, mastered = 0;
        const now = new Date();
        const words = wordsOf(deck);

        words.forEach(word => {
            const card = cardFor(word.lemma);
            if (!card) return;
            inDeck++;
            if ((card.reviews || 0) >= 3) mastered++;
            if (!card.nextReview || new Date(card.nextReview) <= now) due++;
        });

        return {
            total: words.length,
            inDeck: inDeck,
            due: due,
            mastered: mastered,
            missing: words.length - inDeck
        };
    }

    // My Deck is every card, whatever put it there. It is the honest total:
    // the other decks are windows onto the same pile.
    function myDeck() {
        return {
            id: 'mine',
            kind: 'mine',
            name: 'All my words',
            words: srsDeck.map(card => ({
                lemma: card.spanish,
                translation: card.english,
                pos: card.type,
                source: card.source
            }))
        };
    }

    // Where a card came from, in words. Cards saved before provenance was
    // recorded have no source, and say so rather than guessing.
    function originOf(source) {
        if (!source) return '';
        if (source === 'reading') return 'from reading';
        const custom = myDecks.find(d => d.id === source);
        if (custom) return 'from ' + custom.name;
        const deck = (catalogue.decks || []).find(d => d.id === source);
        if (deck) return 'from ' + deck.name;
        if (source.indexOf('lesson:') === 0) return 'from lesson ' + source.slice(7);
        return '';
    }

    function byId(id) {
        if (id === 'mine') return myDeck();
        const custom = myDecks.find(deck => deck.id === id);
        if (custom) return custom;
        return (catalogue.decks || []).find(deck => deck.id === id) || null;
    }

    // ----------------------------------------
    // DATA — My Decks (personal, editable collections)
    // ----------------------------------------
    function myDecksKey() {
        return Lang.key('myDecks');
    }

    function loadMyDecks() {
        try {
            const saved = localStorage.getItem(myDecksKey());
            myDecks = saved ? JSON.parse(saved) : [];
        } catch (error) {
            console.warn('Decks: could not read saved My Decks.', error);
            myDecks = [];
        }
    }

    function saveMyDecks() {
        try {
            localStorage.setItem(myDecksKey(), JSON.stringify(myDecks));
        } catch (error) {
            console.warn('Decks: could not save My Decks.', error);
        }
    }

    function genId() {
        return 'custom-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 8);
    }

    function listMyDecks() {
        return myDecks.slice().sort((a, b) => a.name.localeCompare(b.name));
    }

    // Every lemma sitting in any My Deck, regardless of which one — used by
    // the Library's text analysis to flag "already in your decks" without
    // caring which deck it's in.
    function allMyDeckLemmas() {
        const set = new Set();
        myDecks.forEach(d => d.words.forEach(w => set.add(w.lemma)));
        return set;
    }

    // Adds a word to a stored deck (not the editor draft — see addWordToDraft
    // for that). Used by the "Add to deck" picker, which writes straight
    // through since there is no surrounding form to save. Resolving a
    // manually-typed word to the canonical lexicon entry, where possible,
    // keeps a My Deck from drifting into its own private vocabulary.
    function addWordToDeck(deckId, lemma, translation, pos) {
        const deck = myDecks.find(d => d.id === deckId);
        if (!deck) return false;
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean || deck.words.some(w => w.lemma === clean)) return false;

        const known = Lexicon.define(clean);
        deck.words.push({
            lemma: clean,
            translation: translation || (known && known.en) || '',
            pos: pos || (known && known.type) || ''
        });
        saveMyDecks();
        return true;
    }

    function removeWordFromDeck(deckId, lemma) {
        const deck = myDecks.find(d => d.id === deckId);
        if (!deck) return;
        deck.words = deck.words.filter(w => w.lemma !== lemma);
        saveMyDecks();
    }

    // Deleting a deck only removes the membership list. The words themselves,
    // and any SRS cards built from them, are untouched — they may still
    // belong to other decks, or to nothing at all, same as any other word.
    function deleteMyDeck(deckId) {
        myDecks = myDecks.filter(d => d.id !== deckId);
        saveMyDecks();
        if (openDeck === deckId) openDeck = null;
    }

    // ----------------------------------------
    // ACTIONS — review & bulk-add (Parlour Decks and My Decks alike)
    // ----------------------------------------
    // Adding a deck respects the daily new-word cap: it is there to stop a
    // learner burying themselves, and a button marked "add 20 words" is
    // exactly the moment that matters. This is the one place deck membership
    // turns into SRS activation — reviewing a deck brings its words into the
    // shared schedule, rather than membership doing that on its own.
    function addDeck(id) {
        const deck = byId(id);
        if (!deck) return;

        let added = 0, blocked = 0;
        wordsOf(deck).forEach(word => {
            if (cardFor(word.lemma)) return;
            if (!canAddNewWord()) { blocked++; return; }
            srsDeck.push(Object.assign({
                spanish: word.lemma,
                english: word.translation || 'unknown',
                type: word.pos || 'unknown',
                source: deck.id,
                added: new Date().toISOString()
            }, newCardSchedule()));
            recordNewWord();
            added++;
        });

        saveDeck();
        render();

        if (blocked) {
            alert(added
                ? `Added ${added}. The remaining ${blocked} would go past today's new-word limit — they will be here tomorrow.`
                : `That would go past today's new-word limit of ${NEW_WORDS_DAILY_CAP}. Try again tomorrow.`);
        }
    }

    function reviewDeck(id) {
        const deck = id === 'all' ? null : byId(id);
        startReviewSession(deck ? wordsOf(deck).map(w => w.lemma) : null,
                           deck ? deck.name : 'All decks');
    }

    // ----------------------------------------
    // EDITOR — create / edit a My Deck
    // ----------------------------------------
    // The editor works on a draft copy so "Cancel" is honest — nothing is
    // written to storage until Save. Word add/remove happen against the
    // draft too, for the same reason: they are part of the same commit as
    // the name and description, not separate actions.
    function openCreateDeck() {
        draft = { id: null, name: '', description: '', words: [] };
        Lexicon.load();     // warm the dictionary before the learner starts typing
        render();
    }

    function openEditDeck(id) {
        const deck = myDecks.find(d => d.id === id);
        if (!deck) return;
        draft = {
            id: deck.id,
            name: deck.name,
            description: deck.description || '',
            words: deck.words.slice()
        };
        Lexicon.load();
        render();
    }

    function closeEditor() {
        draft = null;
        render();
    }

    function saveDraft() {
        const name = (draft.name || '').trim();
        if (!name) {
            alert('Give the deck a name first.');
            return;
        }
        const description = (draft.description || '').trim();

        if (draft.id) {
            const deck = myDecks.find(d => d.id === draft.id);
            deck.name = name;
            deck.description = description;
            deck.words = draft.words;
        } else {
            myDecks.push({
                id: genId(), kind: 'custom', name, description,
                created: new Date().toISOString(),
                words: draft.words
            });
        }
        saveMyDecks();
        draft = null;
        render();
    }

    function deleteDraft() {
        if (!draft.id) return;
        if (!confirm(`Delete "${draft.name}"? Its words keep their place in your review deck.`)) return;
        deleteMyDeck(draft.id);
        draft = null;
        render();
    }

    function addWordToDraft(lemma, translation, pos) {
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean || draft.words.some(w => w.lemma === clean)) return;
        draft.words.push({ lemma: clean, translation: translation || '', pos: pos || '' });
        render();
    }

    function addManualWordToDraft(raw) {
        const clean = String(raw || '').toLowerCase().trim();
        if (!clean) return;
        if (draft.words.some(w => w.lemma === clean)) return;
        const known = Lexicon.define(clean);
        if (known) {
            addWordToDraft(clean, known.en, known.type);
            return;
        }
        const translation = prompt(`"${clean}" isn't in the Parlour dictionary yet. What does it mean?`);
        if (translation === null) return;
        addWordToDraft(clean, translation.trim(), '');
    }

    function removeWordFromDraft(lemma) {
        draft.words = draft.words.filter(w => w.lemma !== lemma);
        render();
    }

    // Debounced so a fast typist doesn't run a full-dictionary scan on every
    // keystroke. Rendered straight into the results container rather than
    // through the normal render() path, so the search field itself never
    // loses focus while the learner is typing.
    let searchTimer = null;
    function onEditorSearch(query) {
        clearTimeout(searchTimer);
        searchTimer = setTimeout(() => renderEditorResults(query), 150);
    }

    async function renderEditorResults(query) {
        const host = document.getElementById('dk-editor-results');
        if (!host) return;
        const q = (query || '').trim();
        if (!q) { host.innerHTML = ''; return; }

        if (!Lexicon.isLoaded()) {
            host.innerHTML = '<p class="dk-picker-loading">Loading dictionary…</p>';
            await Lexicon.load();
            const current = document.getElementById('dk-editor-search');
            if (!current || current.value.trim() !== q) return;
        }

        // Shortened here, once — feeds both the preview text and the
        // data-editor-add-en attribute the click handler below reads to
        // build the draft word, so what's added matches what was shown.
        const results = Lexicon.search(q, 8)
            .map(r => Object.assign({}, r, { translation: Lexicon.shortGloss(r.translation) }));
        const already = new Set(draft.words.map(w => w.lemma));

        host.innerHTML = `
            <ul class="dk-picker-results">
                ${results.map(r => `
                    <li>
                        <button class="dk-picker-result" data-editor-add="${esc(r.lemma)}"
                            data-editor-add-en="${esc(r.translation || '')}"
                            data-editor-add-pos="${esc(r.pos || '')}"
                            ${already.has(r.lemma) ? 'disabled' : ''}>
                            <span class="dk-picker-result-es">${esc(withArticle(r.lemma))}</span>
                            <span class="dk-picker-result-en">${esc(r.translation || '—')}</span>
                            ${already.has(r.lemma) ? '<span class="dk-picker-result-added">✓</span>' : ''}
                        </button>
                    </li>
                `).join('')}
            </ul>
            <button class="dk-picker-manual" data-editor-add-manual="${esc(q)}">
                Not here? Add "${esc(q)}" yourself
            </button>
        `;

        host.querySelectorAll('[data-editor-add]').forEach(el => {
            el.onclick = function () {
                addWordToDraft(
                    el.getAttribute('data-editor-add'),
                    el.getAttribute('data-editor-add-en'),
                    el.getAttribute('data-editor-add-pos')
                );
                const search = document.getElementById('dk-editor-search');
                if (search) { search.value = ''; search.focus(); }
                host.innerHTML = '';
            };
        });
        host.querySelectorAll('[data-editor-add-manual]').forEach(el => {
            el.onclick = function () {
                addManualWordToDraft(el.getAttribute('data-editor-add-manual'));
                const search = document.getElementById('dk-editor-search');
                if (search) { search.value = ''; search.focus(); }
                host.innerHTML = '';
            };
        });
    }

    function editorHtml() {
        const isNew = !draft.id;
        const rows = draft.words.map(w => `
            <li class="dk-word">
                <span class="dk-word-es">${esc(withArticle(w.lemma))}</span>
                <span class="dk-word-en">${esc(Lexicon.shortGloss(w.translation) || '—')}</span>
                <button class="dk-word-remove" data-editor-remove="${esc(w.lemma)}"
                    aria-label="Remove ${esc(w.lemma)}">×</button>
            </li>
        `).join('');

        return `
            <button class="dk-back" data-editor-cancel="1">← My Decks</button>
            <div class="dk-editor">
                <h3 class="dk-editor-title">${isNew ? 'Create a deck' : 'Edit deck'}</h3>

                <label class="dk-editor-label" for="dk-editor-name">Name</label>
                <input id="dk-editor-name" class="dk-editor-input" type="text"
                    placeholder="e.g. Travel essentials" value="${esc(draft.name)}" maxlength="60">

                <label class="dk-editor-label" for="dk-editor-desc">Description (optional)</label>
                <textarea id="dk-editor-desc" class="dk-editor-input dk-editor-textarea"
                    placeholder="What this deck is for" maxlength="200">${esc(draft.description)}</textarea>

                <label class="dk-editor-label" for="dk-editor-search">Add vocabulary</label>
                <input id="dk-editor-search" class="dk-editor-input" type="text"
                    placeholder="Search in ${Lang.name()} or English…" autocomplete="off">
                <div id="dk-editor-results" class="dk-picker-panel"></div>

                <ul class="dk-words dk-editor-words">
                    ${rows || '<li class="dk-empty">No words yet. Search above to add some.</li>'}
                </ul>

                <div class="dk-actions dk-editor-actions">
                    <button class="btn-primary" data-editor-save="1">Save deck</button>
                    ${!isNew ? '<button class="dk-danger" data-editor-delete="1">Delete deck</button>' : ''}
                </div>
            </div>
        `;
    }

    function wireEditor(host) {
        const name = document.getElementById('dk-editor-name');
        const desc = document.getElementById('dk-editor-desc');
        const search = document.getElementById('dk-editor-search');
        if (name) name.oninput = e => { draft.name = e.target.value; };
        if (desc) desc.oninput = e => { draft.description = e.target.value; };
        if (search) search.oninput = e => onEditorSearch(e.target.value);

        host.querySelectorAll('[data-editor-remove]').forEach(el => {
            el.onclick = function () { removeWordFromDraft(el.getAttribute('data-editor-remove')); };
        });
        host.querySelectorAll('[data-editor-cancel]').forEach(el => { el.onclick = closeEditor; });
        host.querySelectorAll('[data-editor-save]').forEach(el => { el.onclick = saveDraft; });
        host.querySelectorAll('[data-editor-delete]').forEach(el => { el.onclick = deleteDraft; });
    }

    // ----------------------------------------
    // PICKER — "Add to deck" from anywhere a word appears
    // ----------------------------------------
    // A standalone overlay, independent of the Decks tab's own render cycle,
    // so it can be opened from the reader (or any future word-tapping
    // surface) without navigating away from what the learner was doing.
    // Adding a word here is membership only: it does not touch the SRS
    // schedule, so a learner can stash 50 words in a deck without being
    // asked to learn 50 words today.
    function ensurePicker() {
        let el = document.getElementById('deck-picker');
        if (el) return el;
        el = document.createElement('div');
        el.id = 'deck-picker';
        document.body.appendChild(el);
        return el;
    }

    function closePicker() {
        const el = document.getElementById('deck-picker');
        if (el) el.innerHTML = '';
    }

    function pickerListHtml(isDone) {
        const decks = listMyDecks();
        if (!decks.length) {
            return '<p class="dk-empty">No decks yet — create one below.</p>';
        }
        return `
            <ul class="dk-picker-list">
                ${decks.map(d => {
                    const done = isDone(d);
                    return `
                        <li>
                            <button class="dk-picker-deck" data-picker-add="${esc(d.id)}" ${done ? 'disabled' : ''}>
                                <span>${esc(d.name)}</span>
                                <span class="dk-picker-deck-count">${done ? '✓ added' : d.words.length + ' words'}</span>
                            </button>
                        </li>
                    `;
                }).join('')}
            </ul>
        `;
    }

    // Shared shell for both "Add to deck" pickers below — one word from the
    // reader, or a batch from the Library's vocabulary selection. `isDone`
    // decides when a deck row shows as already satisfied; `onPick`/`onCreate`
    // do the actual adding for a chosen (or newly created) deck.
    function openPicker(titleHtml, isDone, onPick, onCreate) {
        loadMyDecks();
        if (typeof Lexicon !== 'undefined') Lexicon.load();

        const host = ensurePicker();
        host.innerHTML = `
            <div class="wp-overlay" id="deck-picker-overlay">
                <div class="wp-sheet dk-picker-sheet">
                    <div class="wp-header">
                        <h2 class="wp-word">${titleHtml}</h2>
                        <button class="wp-close" data-picker-close="1" aria-label="Close">×</button>
                    </div>
                    <div id="deck-picker-list">${pickerListHtml(isDone)}</div>
                    <div class="dk-picker-create">
                        <input id="deck-picker-new-name" class="dk-editor-input" type="text"
                            placeholder="New deck name" maxlength="60">
                        <button class="dk-secondary" data-picker-create="1">+ Create &amp; add</button>
                    </div>
                </div>
            </div>
        `;

        function refreshList() {
            const list = document.getElementById('deck-picker-list');
            if (list) list.innerHTML = pickerListHtml(isDone);
            wireList();
        }

        function wireList() {
            host.querySelectorAll('[data-picker-add]').forEach(el => {
                el.onclick = function () {
                    onPick(el.getAttribute('data-picker-add'));
                    refreshList();
                };
            });
        }

        host.querySelectorAll('[data-picker-close]').forEach(el => { el.onclick = closePicker; });
        const overlay = document.getElementById('deck-picker-overlay');
        if (overlay) overlay.onclick = function (e) { if (e.target === overlay) closePicker(); };

        host.querySelectorAll('[data-picker-create]').forEach(el => {
            el.onclick = function () {
                const input = document.getElementById('deck-picker-new-name');
                const name = (input.value || '').trim();
                if (!name) { input.focus(); return; }
                myDecks.push({
                    id: genId(), kind: 'custom', name, description: '',
                    created: new Date().toISOString(), words: []
                });
                saveMyDecks();
                onCreate(myDecks[myDecks.length - 1].id);
                input.value = '';
                refreshList();
            };
        });

        wireList();
    }

    function openAddToDeckPicker(lemma, translation, pos) {
        const clean = String(lemma || '').toLowerCase().trim();
        if (!clean) return;
        const add = deckId => addWordToDeck(deckId, clean, translation, pos);
        openPicker(
            `Add "${esc(withArticle(clean))}" to a deck`,
            deck => deck.words.some(w => w.lemma === clean),
            add, add
        );
    }

    // Same overlay, for several words at once — the Library's vocabulary
    // selection view (see engine/library.js) sends every checked word to one
    // deck in a single action rather than one popup per word.
    function openBulkAddPicker(items) {
        const list = (items || [])
            .filter(it => it && it.lemma)
            .map(it => Object.assign({}, it, { lemma: String(it.lemma).toLowerCase().trim() }));
        if (!list.length) return;

        const addAll = deckId => { list.forEach(it => addWordToDeck(deckId, it.lemma, it.translation, it.pos)); };
        openPicker(
            `Add ${list.length} ${list.length === 1 ? 'word' : 'words'} to a deck`,
            deck => list.every(it => deck.words.some(w => w.lemma === it.lemma)),
            addAll, addAll
        );
    }

    // ----------------------------------------
    // RENDER
    // ----------------------------------------
    function esc(value) {
        return (typeof UI !== 'undefined' && UI.escape)
            ? UI.escape(value) : String(value == null ? '' : value);
    }

    // "gato" -> "el gato". Lexicon owns the formatting (Library uses the same
    // one); this is a live lookup rather than anything stored on the word,
    // since the dictionary may not have been loaded yet when the word was
    // first saved.
    function withArticle(lemma) {
        return (typeof Lexicon !== 'undefined') ? Lexicon.withArticle(lemma) : lemma;
    }

    function deckCard(deck) {
        const s = statusOf(deck);
        const percent = s.total ? Math.round((s.inDeck / s.total) * 100) : 0;
        const preview = wordsOf(deck).slice(0, 5).map(w => withArticle(w.lemma)).join(' · ');

        return `
            <button class="dk-card" data-open-deck="${esc(deck.id)}">
                <span class="dk-card-top">
                    ${deck.label ? `<span class="dk-num">${esc(deck.label)}</span>` : ''}
                    <span class="dk-name">${esc(deck.name)}</span>
                    ${s.due ? `<span class="dk-due">${s.due}</span>` : ''}
                </span>
                <span class="dk-preview">${esc(preview) || 'No words yet'}</span>
                <span class="dk-meter"><span class="dk-fill" style="width:${percent}%"></span></span>
                <span class="dk-meta">
                    <span>${s.total} ${s.total === 1 ? 'word' : 'words'}</span>
                    <span>${s.inDeck ? s.inDeck + ' in your deck' : 'none added yet'}</span>
                </span>
            </button>
        `;
    }

    // My Decks and Parlour Decks are tabs on one subnav — same lt-subnav
    // component the Library uses for Parlour/Saved/My Texts — rather than
    // two stacked lists, so a learner isn't scrolling past a wall of My
    // Decks to reach the course's 300-odd curated ones, or vice versa.
    function myDecksSectionHtml() {
        const decks = listMyDecks();
        return `
            <div class="lt-index-head">
                <p class="dk-group-blurb">Your own collections. Add any word, from anywhere in Parlour.</p>
                <button class="dk-secondary dk-create-btn" data-create-deck="1">+ Create deck</button>
            </div>
            ${decks.length
                ? `<div class="dk-grid">${decks.map(deckCard).join('')}</div>`
                : '<p class="dk-empty">No decks yet. Create one to start collecting words.</p>'}
        `;
    }

    function parlourDecksSectionHtml() {
        const decks = catalogue.decks || [];
        const groups = KIND_ORDER.map(kind => {
            const group = decks.filter(deck => deck.kind === kind);
            if (!group.length) return '';
            return `
                <section class="dk-group">
                    <button class="dk-group-header" data-group-toggle="${kind}" aria-expanded="false">
                        <span>
                            <span class="dk-group-title">${esc(KIND_LABEL[kind])}</span>
                            <span class="dk-group-count">${group.length}</span>
                        </span>
                        <span class="dk-group-arrow" id="dk-group-arrow-${kind}" aria-hidden="true">▶</span>
                    </button>
                    <div class="dk-group-body hidden" id="dk-group-body-${kind}">
                        <p class="dk-group-blurb">${KIND_BLURB[kind]}</p>
                        <div class="dk-grid">${group.map(deckCard).join('')}</div>
                    </div>
                </section>
            `;
        }).join('');

        return `
            <p class="dk-group-blurb">Curated by the course. Browse and review them, or add
                their words to a deck of your own.</p>
            ${groups || '<p class="dk-empty">No decks for this course yet.</p>'}
        `;
    }

    function indexHtml() {
        const mine = myDeck();
        const mineStatus = statusOf(mine);
        const myDeckCount = listMyDecks().length;
        const parlourCount = (catalogue.decks || []).length;
        const knownCount = (typeof knownWords !== 'undefined') ? knownWords.length : 0;

        return `
            <div class="dk-top">
                <div class="dk-mine">
                    <h3 class="dk-group-title">All my words</h3>
                    <p class="dk-group-blurb">Every word you have taken on, from wherever you met it.</p>
                    <p class="dk-big">${mineStatus.total}
                        <span class="dk-of">reviewing</span></p>
                    <p class="dk-meta-line">${mineStatus.due} due now ·
                        ${mineStatus.mastered} reviewed three times or more</p>
                </div>
                <div class="dk-mine">
                    <h3 class="dk-group-title">My Dictionary</h3>
                    <p class="dk-group-blurb">Words you already know — retired from review.</p>
                    <p class="dk-big">${knownCount}
                        <span class="dk-of">known</span></p>
                    <p class="dk-meta-line">${mineStatus.total + knownCount} words total</p>
                </div>
                <div class="dk-actions">
                    <button class="btn-primary" data-review-deck="all"
                        ${mineStatus.due ? '' : 'disabled'}>
                        Review all${mineStatus.due ? ` (${mineStatus.due})` : ''}
                    </button>
                    <button data-open-deck="mine" class="dk-secondary">Browse all my words</button>
                    <button data-open-dictionary="1" class="dk-secondary">My Dictionary</button>
                </div>
            </div>
            <nav class="lt-subnav" id="dk-subnav">
                <button class="lt-subnav-btn${activeSection === 'mine' ? ' active' : ''}"
                    data-dk-tab="mine">My Decks <span class="dk-group-count">${myDeckCount}</span></button>
                <button class="lt-subnav-btn${activeSection === 'parlour' ? ' active' : ''}"
                    data-dk-tab="parlour">Parlour Decks <span class="dk-group-count">${parlourCount}</span></button>
            </nav>
            ${activeSection === 'parlour' ? parlourDecksSectionHtml() : myDecksSectionHtml()}
        `;
    }

    function detailHtml(deck) {
        const s = statusOf(deck);
        const isCustom = deck.kind === 'custom';
        // "All my words" has no membership list of its own to edit — it is
        // just the shared SRS pile — so removing a word here means deleting
        // its card outright, not unlinking it from a deck.
        const removable = deck.id === 'mine';

        const rows = wordsOf(deck).map(word => {
            const card = cardFor(word.lemma);
            const state = !card ? 'not added'
                : (card.reviews || 0) >= 3 ? 'mastered'
                : (card.reviews || 0) >= 1 ? 'learning'
                : 'new';
            // Origin is worth showing in My Deck, where words arrive from
            // everywhere. In a lesson deck every word has the same origin, so
            // printing it on each row would be noise.
            const origin = deck.id === 'mine' ? originOf(word.source) : '';

            return `
                <li class="dk-word dk-word-${state.replace(' ', '-')}">
                    <span class="dk-word-es">${esc(withArticle(word.lemma))}${
                        typeof Speech !== 'undefined' ? Speech.button(word.lemma) : ''}</span>
                    <span class="dk-word-en">${esc(word.translation)}${
                        origin ? `<span class="dk-word-origin">${esc(origin)}</span>` : ''}</span>
                    <span class="dk-word-state">${state}</span>
                    ${removable ? `<button class="dk-word-remove" data-remove-card="${esc(word.lemma)}"
                        aria-label="Remove ${esc(word.lemma)}">×</button>` : ''}
                </li>
            `;
        }).join('');

        return `
            <button class="dk-back" data-close-deck="1">← All decks</button>
            <div class="dk-detail-head">
                <h3>${esc(deck.name)}</h3>
                ${deck.description ? `<p class="dk-detail-desc">${esc(deck.description)}</p>` : ''}
                <p>${s.inDeck} of ${s.total} in your review deck · ${s.due} due · ${s.mastered} mastered</p>
                <div class="dk-actions">
                    <button class="btn-primary" data-review-deck="${esc(deck.id)}"
                        ${s.due ? '' : 'disabled'}>
                        Review this deck${s.due ? ` (${s.due})` : ''}
                    </button>
                    ${s.missing ? `<button class="dk-secondary" data-add-deck="${esc(deck.id)}">
                        Add ${s.missing} to review</button>` : ''}
                    ${isCustom ? `<button class="dk-secondary" data-edit-deck="${esc(deck.id)}">Edit deck</button>` : ''}
                </div>
            </div>
            <ul class="dk-words${removable ? ' dk-words-removable' : ''}">${rows || '<li class="dk-empty">No words yet.</li>'}</ul>
        `;
    }

    // Words the learner has said they know, whichever way they said it
    // (lesson-end choice, graduated out of SRS, or added by hand below).
    // Nothing here is scheduled — that's the point — so the list is just
    // alphabetical rather than sorted by any review state.
    function dictionaryHtml() {
        const words = (typeof knownWords !== 'undefined')
            ? knownWords.slice().sort((a, b) => a.spanish.localeCompare(b.spanish))
            : [];

        const rows = words.map(w => `
            <li class="dk-word">
                <span class="dk-word-es">${esc(withArticle(w.spanish))}${
                    typeof Speech !== 'undefined' ? Speech.button(w.spanish) : ''}</span>
                <span class="dk-word-en">${esc(Lexicon.shortGloss(w.english))}</span>
                <button class="dk-secondary" data-move-to-review="${esc(w.spanish)}">Back to review</button>
            </li>
        `).join('');

        return `
            <button class="dk-back" data-close-dictionary="1">← All decks</button>
            <div class="dk-detail-head">
                <h3>My Dictionary</h3>
                <p>Words you already know stay out of review. Add one any time you'd
                    rather not keep seeing it.</p>
            </div>
            <div class="dk-dictionary-add">
                <input type="text" id="dict-add-input" class="lsn-input" placeholder="Add a word, e.g. vivir">
                <button class="dk-secondary" id="dict-add-btn">+ Add</button>
            </div>
            <p id="dict-add-feedback" class="dk-meta-line"></p>
            <ul class="dk-words">${rows || '<li class="dk-empty">No known words yet.</li>'}</ul>
        `;
    }

    function addKnownWordByHand() {
        const input = document.getElementById('dict-add-input');
        const feedback = document.getElementById('dict-add-feedback');
        if (!input) return;

        const raw = input.value.trim().toLowerCase();
        if (!raw) return;

        const entry = (typeof Lexicon !== 'undefined') ? Lexicon.define(raw) : null;
        if (!entry) {
            if (feedback) feedback.textContent = `Couldn't find "${raw}" in the dictionary.`;
            return;
        }

        const added = (typeof addKnownWord === 'function') && addKnownWord(raw, entry.en, entry.type, 'manual');
        if (feedback) feedback.textContent = added ? `Added "${raw}."` : `"${raw}" is already known.`;
        input.value = '';
        render();
    }

    // Deleting a word from "All my words" deletes its SRS card — there is
    // nothing else to remove it from. That is different from removing a word
    // from a My Deck, which only ever touches membership; this is the one
    // place in the UI that reaches into the card pile itself, so it asks
    // first.
    function removeFromAllWords(lemma) {
        if (!confirm(`Remove "${lemma}" from your deck? This deletes its review history.`)) return;
        srsDeck = srsDeck.filter(card => card.spanish !== lemma);
        saveDeck();
        render();
    }

    async function render() {
        const host = document.getElementById('decks-root');
        if (!host) return;

        await load();

        if (draft) {
            host.innerHTML = editorHtml();
            wireEditor(host);
            return;
        }

        if (showDictionary) {
            host.innerHTML = dictionaryHtml();
            host.querySelectorAll('[data-close-dictionary]').forEach(el => {
                el.onclick = function () { showDictionary = false; render(); };
            });
            host.querySelectorAll('[data-move-to-review]').forEach(el => {
                el.onclick = function () {
                    if (typeof moveKnownToReview === 'function') {
                        moveKnownToReview(el.getAttribute('data-move-to-review'));
                    }
                    render();
                };
            });
            const addBtn = document.getElementById('dict-add-btn');
            if (addBtn) addBtn.onclick = addKnownWordByHand;
            const addInput = document.getElementById('dict-add-input');
            if (addInput) addInput.onkeydown = e => { if (e.key === 'Enter') addKnownWordByHand(); };
            return;
        }

        const deck = openDeck ? byId(openDeck) : null;
        host.innerHTML = deck ? detailHtml(deck) : indexHtml();

        host.querySelectorAll('[data-group-toggle]').forEach(el => {
            el.onclick = function () {
                const kind = el.getAttribute('data-group-toggle');
                const body = document.getElementById('dk-group-body-' + kind);
                const arrow = document.getElementById('dk-group-arrow-' + kind);
                if (!body) return;
                const nowOpen = body.classList.toggle('hidden') === false;
                el.setAttribute('aria-expanded', String(nowOpen));
                if (arrow) arrow.textContent = nowOpen ? '▼' : '▶';
            };
        });
        host.querySelectorAll('[data-open-deck]').forEach(el => {
            el.onclick = function () { openDeck = el.getAttribute('data-open-deck'); render(); };
        });
        host.querySelectorAll('[data-open-dictionary]').forEach(el => {
            el.onclick = function () { showDictionary = true; render(); };
        });
        host.querySelectorAll('[data-close-deck]').forEach(el => {
            el.onclick = function () { openDeck = null; render(); };
        });
        host.querySelectorAll('[data-add-deck]').forEach(el => {
            el.onclick = function () { addDeck(el.getAttribute('data-add-deck')); };
        });
        host.querySelectorAll('[data-remove-card]').forEach(el => {
            el.onclick = function () { removeFromAllWords(el.getAttribute('data-remove-card')); };
        });
        host.querySelectorAll('[data-review-deck]').forEach(el => {
            el.onclick = function () { reviewDeck(el.getAttribute('data-review-deck')); };
        });
        host.querySelectorAll('[data-create-deck]').forEach(el => {
            el.onclick = function () { openCreateDeck(); };
        });
        host.querySelectorAll('[data-dk-tab]').forEach(el => {
            el.onclick = function () { activeSection = el.getAttribute('data-dk-tab'); render(); };
        });
        host.querySelectorAll('[data-edit-deck]').forEach(el => {
            el.onclick = function () { openEditDeck(el.getAttribute('data-edit-deck')); };
        });
    }

    return {
        render, load, statusOf, myDeck, addDeck, reviewDeck,
        openAddToDeckPicker, openBulkAddPicker, allMyDeckLemmas
    };
})();
