// ============================================
// LEARNER MODEL — "what does the learner actually know"
// ============================================
// Step 2 of the Learner model & personalized path roadmap initiative (see
// ROADMAP.md), built on top of step 1 (engine/learnerPath.js). Where
// LearnerPath answers "where is the learner in the curriculum" (a position),
// this answers "what do they actually know" (a competence signal) — grammar
// skills and vocabulary each classified into one of four states:
// not-yet-seen / weak / developing / strong.
//
// Four separate, differently-shaped evidence stores exist today with no
// shared identifier space:
//   - engine/recycle.js's recycleSchedule: exercise-id -> SM-2 card, only
//     joinable to a "skill" via grammar-index.json's bySkill map. Since
//     step 6, every teaches-tagged exercise records here on its very first
//     encounter, not just when later redrawn into a recycle block.
//   - engine/srs.js's srsDeck (active SM-2 cards) and knownWords (graduated/
//     manually-known words, which drop all SM-2 evidence on graduation).
//   - engine/leveltest.js's testResults: a ranked "weakest" topic-id list
//     per attempt, never cross-referenced against the recycle schedule.
//   - engine/drillHistory.js's per-driller accuracy-% classification (step
//     6), for the drillers with no SM-2 signal of their own — kept on its
//     own accuracy scale rather than forced onto this module's ease scale,
//     since the two measure different things.
// This module folds all of these into one per-skill/per-word/per-driller
// classification, and adds a prerequisite/dependency query surface
// (content/<lang>/indexes/
// skill-prereqs.json — a hand-authored file, deliberately NOT inside
// grammar-index.json, which is machine-regenerated by
// scripts/build_grammar_index.py and would silently discard anything added
// there).
//
// engine/recommend.js's weakestSkill()/weakestWords() were the first, narrow
// slice of this (recycle/srs evidence only, binary weak-or-null) and have
// moved here as weakSkills()/weakWords() — recommend.js now calls into this
// module instead of computing its own signal, same migration pattern step 1
// used for unitFor()/lastCompletedLessonId().

const LearnerModel = (function () {
    'use strict';

    // Skills/words with fewer reviews than this don't carry enough signal
    // to call "weak" rather than "barely seen yet" — moved here verbatim
    // from engine/recommend.js.
    const MIN_REVIEWED = 2;
    const MIN_REVIEWED_WORDS = 3;
    const WEAK_WORDS_LIMIT = 8;

    // Ease-classification cutoffs, derived from engine/srs.js's SRS_CONFIG
    // (START_EASE 2.5, range 1.3-3.0). 2.0 takes real sustained struggle to
    // reach from the starting point; 2.6 requires having climbed above it
    // at least once via an "easy" rating — real demonstrated ease, not just
    // "hasn't been rated down yet."
    const WEAK_EASE_CEILING = 2.0;
    const STRONG_EASE_FLOOR = 2.6;

    const STATES = ['not-yet-seen', 'weak', 'developing', 'strong'];

    function classifyEase(avgEase) {
        if (avgEase < WEAK_EASE_CEILING) return 'weak';
        if (avgEase < STRONG_EASE_FLOOR) return 'developing';
        return 'strong';
    }

    // One tier down, floored at 'weak' — used when a level-test miss
    // contradicts otherwise-solid recycle evidence. A single test miss is
    // real but partial evidence (one question, no repeat-testing, no
    // magnitude): it shouldn't unilaterally overrule months of recycle
    // history by nuking straight to 'weak', but it shouldn't be silently
    // ignored either.
    function downgrade(state) {
        const i = STATES.indexOf(state);
        return STATES[Math.max(1, i - 1)]; // never below 'weak' (index 1)
    }

    async function _grammarIndex() {
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return null;
        try {
            return await Content.json(Lang.content('indexes/grammar-index.json'));
        } catch (error) {
            return null;
        }
    }

    // Cached per course after first fetch — a hand-authored file that
    // rarely changes, unlike the schedules this module reads live. Missing
    // or unparsable degrades to {}, same defensive pattern
    // loadRecycleSchedule() (engine/recycle.js) already uses, so an absent
    // or half-authored prereqs file is silent, not a crash.
    let _prereqsCache = null;
    let _prereqsCacheCourse = null;

    async function _prereqs() {
        const course = (typeof Lang !== 'undefined') ? Lang.key('') : '';
        if (_prereqsCache && _prereqsCacheCourse === course) return _prereqsCache;
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return {};
        try {
            _prereqsCache = await Content.json(Lang.content('indexes/skill-prereqs.json'));
        } catch (error) {
            _prereqsCache = {};
        }
        _prereqsCacheCourse = course;
        return _prereqsCache;
    }

    // ----------------------------------------
    // GRAMMAR SKILLS
    // ----------------------------------------

    // Every stored level-test result's weakest[] list, flattened into one
    // Set of flagged skill ids — checked as a boolean vote per skill (the
    // stored result already discards per-topic magnitude, so this can't be
    // more than a flag).
    function _levelTestFlags() {
        const flags = new Set();
        if (typeof LevelTest === 'undefined' || typeof LEVEL_ORDER === 'undefined') return flags;
        LEVEL_ORDER.forEach(level => {
            const result = LevelTest.resultFor(level);
            (result && result.weakest || []).forEach(id => flags.add(id));
        });
        return flags;
    }

    // The full classification for one grammar skill, folding recycle-
    // schedule evidence (exercise-level ease, joined via grammar-index.json)
    // with the level-test vote. See the module header for the shape of each
    // evidence source and the file's own comments below for the combining
    // rule.
    async function skillState(skillId) {
        const index = await _grammarIndex();
        const schedule = (typeof loadRecycleSchedule === 'function') ? loadRecycleSchedule() : {};
        const refs = (index && index.bySkill && index.bySkill[skillId]) || [];

        let totalEase = 0, seen = 0;
        refs.forEach(entry => {
            const card = schedule[entry.id];
            if (card && card.reviews > 0) {
                seen++;
                totalEase += card.ease;
            }
        });

        const recycle = seen > 0 ? { seen, avgEase: totalEase / seen } : null;
        const levelTestFlagged = _levelTestFlags().has(skillId);

        let state;
        if (!recycle) {
            state = levelTestFlagged ? 'weak' : 'not-yet-seen';
        } else if (seen === 1) {
            state = levelTestFlagged ? 'weak' : 'developing';
        } else {
            const base = classifyEase(recycle.avgEase);
            state = levelTestFlagged ? downgrade(base) : base;
        }

        return { skillId, state, recycle, levelTestFlagged };
    }

    // The skills with real trouble signal, worst first — replaces
    // engine/recommend.js's weakestSkill(), returning the full classified
    // shape (a strict superset: skillId/state/recycle/levelTestFlagged)
    // rather than a bare skill-id string. A skill only appears here once it
    // clears the same MIN_REVIEWED floor weakestSkill() always required, OR
    // is level-test-flagged with no recycle history at all — surfacing that
    // is the actual gap this module closes; today's code silently drops a
    // level-test miss unless recycle evidence also happens to exist.
    async function weakSkills(limit) {
        const index = await _grammarIndex();
        if (!index) return [];
        const schedule = (typeof loadRecycleSchedule === 'function') ? loadRecycleSchedule() : {};
        const flags = _levelTestFlags();

        const results = [];
        Object.keys(index.bySkill || {}).forEach(skillId => {
            const refs = index.bySkill[skillId] || [];
            let totalEase = 0, seen = 0;
            refs.forEach(entry => {
                const card = schedule[entry.id];
                if (card && card.reviews > 0) {
                    seen++;
                    totalEase += card.ease;
                }
            });

            const levelTestFlagged = flags.has(skillId);
            const recycle = seen > 0 ? { seen, avgEase: totalEase / seen } : null;

            let state = null;
            if (!recycle && levelTestFlagged) {
                state = 'weak';
            } else if (recycle && seen >= MIN_REVIEWED) {
                const base = classifyEase(recycle.avgEase);
                state = levelTestFlagged ? downgrade(base) : base;
            }
            // seen === 1 (underpowered) and unflagged recycle-only cases
            // are deliberately excluded from this ranked list, same honesty
            // rule weakestSkill() always applied — "developing on one data
            // point" isn't a confident enough signal to actively recommend
            // practising.

            if (state === 'weak' || state === 'developing') {
                results.push({ skillId, state, recycle, levelTestFlagged });
            }
        });

        // Weak before developing; within a tier, lower ease (or, for a
        // level-test-only flag with no recycle data, treated as worst)
        // sorts first.
        const rank = s => (s.state === 'weak' ? 0 : 1);
        const ease = s => (s.recycle ? s.recycle.avgEase : -1);
        results.sort((a, b) => rank(a) - rank(b) || ease(a) - ease(b));

        return results.slice(0, limit || results.length);
    }

    // ----------------------------------------
    // VOCABULARY
    // ----------------------------------------

    // The classification for one lemma, folding srsDeck (active review) and
    // knownWords (graduated or manually declared). Sync, unlike skillState —
    // both stores are plain in-memory globals kept live by engine/srs.js,
    // same as engine/recommend.js's weakestWords() already assumed.
    function wordState(lemma) {
        if (typeof knownWords !== 'undefined' && Array.isArray(knownWords)) {
            const known = knownWords.find(w => w.spanish === lemma);
            if (known) {
                return {
                    lemma,
                    state: 'strong',
                    verified: !!known.graduated,
                    source: known.graduated ? 'graduated' : 'known'
                };
            }
        }

        if (typeof srsDeck !== 'undefined' && Array.isArray(srsDeck)) {
            const card = srsDeck.find(c => c.spanish === lemma);
            if (card) {
                if (!card.reviews) {
                    return { lemma, state: 'not-yet-seen', verified: false, source: 'srs', ease: card.ease, reviews: 0 };
                }
                let state = classifyEase(card.ease);
                // Fewer than MIN_REVIEWED_WORDS caps the ceiling at
                // 'developing' — not enough repeats to call it 'strong'
                // yet — but does not raise a genuinely low ease, since one
                // bad rating is still real trouble signal.
                if (card.reviews < MIN_REVIEWED_WORDS && state === 'strong') state = 'developing';
                return { lemma, state, verified: false, source: 'srs', ease: card.ease, reviews: card.reviews };
            }
        }

        return { lemma, state: 'not-yet-seen', verified: false, source: 'srs' };
    }

    // The words with the worst average ease among those with real review
    // history — replaces engine/recommend.js's weakestWords(), same honesty
    // rule (returns [] below the review-count floor) but keeps ease/reviews
    // in the returned shape alongside the lemma/translation/pos every
    // caller already expects.
    function weakWords(limit) {
        if (typeof srsDeck === 'undefined' || !Array.isArray(srsDeck)) return [];

        const reviewed = srsDeck.filter(card => card.reviews > 0 && typeof card.ease === 'number');
        if (reviewed.length < MIN_REVIEWED_WORDS) return [];

        return reviewed
            .slice()
            .sort((a, b) => a.ease - b.ease)
            .slice(0, limit || WEAK_WORDS_LIMIT)
            .map(card => ({
                lemma: card.spanish,
                translation: card.english,
                pos: card.type,
                ease: card.ease,
                reviews: card.reviews
            }));
    }

    // ----------------------------------------
    // DRILLERS (moved from engine/recommendationEngine.js)
    // ----------------------------------------
    // Every driller lacking a real competence signal today, mapped to the
    // curriculum lesson that gates its relevance — populated only where a
    // driller's own source comments state a real milestone, not fabricated
    // for the rest. Grammar and Vocabulary aren't listed here: they already
    // have this module's richer SM-2-based signal above. Belongs here, not
    // in RecommendationEngine, for the same reason weakSkills()/weakWords()
    // do: this module tracks what's weak, RecommendationEngine only ranks
    // and presents what this module already found. Uses engine/drillHistory.js's
    // accuracy-% classification as-is (not reconciled onto this module's
    // SM-2 ease scale — a deliberate step-3 decision, since the two measure
    // different things), so this only unifies where the answer to "is the
    // learner weak at X" comes from, not the underlying number scale.
    const DRILLER_UNLOCK = {
        'hu-suffix': 'lesson.a1.22',      // matches hu-suffix.js's own "Unit 5" (plural) comment
        'hu-prefix': 'lesson.a2.01',      // driller's own comment: full prefix system is an A2 topic
        'hu-morphology': 'lesson.a1.51'   // matches hu-suffix.js's "Unit 11+" (case) comment
        // hu-verb, verbs, translation, listening: no gate — none of these
        // four's own header comments state a curriculum-scoping rationale;
        // relevance for them is accuracy-history only.
    };

    const DRILLER_TITLES = {
        verbs: 'Verb Driller',
        translation: 'Translation Driller',
        listening: 'Listening Driller',
        'hu-suffix': 'Suffix Driller',
        'hu-prefix': 'Prefix Driller',
        'hu-morphology': 'Morphology Driller',
        'hu-verb': 'Verb Driller'
    };

    const TRACKED_DRILLERS = Object.keys(DRILLER_TITLES);

    // Mirrors workshop.js's own DRILLERS[].langs / _available() filter —
    // `verbs` is Spanish-only, the hu-* drillers are Hungarian-only.
    function _drillerAvailable(id) {
        if (id === 'verbs') return (typeof Lang !== 'undefined') && Lang.code() === 'es';
        if (id.indexOf('hu-') === 0) return (typeof Lang !== 'undefined') && Lang.code() === 'hu';
        return true;
    }

    function _drillerUnlocked(id) {
        const anchor = DRILLER_UNLOCK[id];
        if (!anchor) return true;
        return (typeof LearnerPath !== 'undefined') ? LearnerPath.isComplete(anchor) : true;
    }

    // A driller becomes eligible once BOTH curriculum-unlocked (or ungated)
    // AND its accuracy history classifies weak — unlocked-but-never-tried
    // stays silent, consistent with weakSkills()'s own underpowered-data
    // rule above.
    function weakDrillers() {
        const candidates = [];
        TRACKED_DRILLERS.forEach(id => {
            if (!_drillerAvailable(id) || !_drillerUnlocked(id)) return;
            const cls = (typeof DrillHistory !== 'undefined') ? DrillHistory.classify(id) : { state: null };
            if (cls.state === 'weak') {
                candidates.push({ drillerId: id, title: DRILLER_TITLES[id], avgAccuracy: cls.avgAccuracy });
            }
        });
        return candidates;
    }

    // ----------------------------------------
    // PREREQUISITES
    // ----------------------------------------

    // Cached synchronously after the first async load — callers that need
    // this synchronously (rendering) should have already triggered a
    // isReady()/prerequisitesFor() call once during page load. Returns []
    // before the first successful fetch, same graceful-empty behaviour as
    // an absent file.
    function prerequisitesFor(skillId) {
        const data = _prereqsCache || {};
        return data[skillId] || [];
    }

    // Advisory, not a mastery gate — matching LevelTest's own stated
    // "advisory, not a gate" philosophy and the roadmap's framing of this
    // whole model as "mostly hidden from the learner." A prerequisite
    // counts as met once the learner has been introduced to it at all
    // (anything but not-yet-seen), not once it's specifically "strong."
    async function isReady(skillId) {
        await _prereqs(); // ensure the cache is populated for prerequisitesFor()
        const prereqIds = prerequisitesFor(skillId);
        if (!prereqIds.length) return { ready: true, missing: [] };

        const missing = [];
        for (const id of prereqIds) {
            const state = await skillState(id);
            if (state.state === 'not-yet-seen') missing.push(id);
        }
        return { ready: missing.length === 0, missing };
    }

    return {
        skillState,
        wordState,
        weakSkills,
        weakWords,
        weakDrillers,
        prerequisitesFor,
        isReady
    };
})();
