// ============================================
// LEARNER MODEL — "what does the learner actually know"
// ============================================
// Step 2 of the Learner model & personalized path roadmap initiative (see
// ROADMAP.md), built on top of step 1 (engine/learnerPath.js). Where
// LearnerPath answers "where is the learner in the curriculum" (a position),
// this answers "what do they actually know" (a competence signal) — grammar
// skills and vocabulary each classified into one of four states:
// not-yet-seen / weak / developing / strong.
//
// Four separate, differently-shaped evidence stores exist today with no
// shared identifier space:
//   - engine/recycle.js's recycleSchedule: exercise-id -> SM-2 card, only
//     joinable to a "skill" via grammar-index.json's bySkill map. Since
//     step 6, every teaches-tagged exercise records here on its very first
//     encounter, not just when later redrawn into a recycle block. Since
//     2026-09-25 the Grammar Driller records here too, including its own
//     bank items as "bank:<id>" (joined by module in _skillRefs()).
//   - engine/srs.js's srsDeck (active SM-2 cards) and knownWords (graduated/
//     manually-known words, which drop all SM-2 evidence on graduation).
//   - engine/leveltest.js's testResults: a ranked "weakest" topic-id list
//     per attempt, never cross-referenced against the recycle schedule.
//   - engine/drillHistory.js's per-driller accuracy-% classification (step
//     6), for the drillers with no SM-2 signal of their own — kept on its
//     own accuracy scale rather than forced onto this module's ease scale,
//     since the two measure different things.
// This module folds all of these into one per-skill/per-word/per-driller
// classification, and adds a prerequisite/dependency query surface
// (content/<lang>/indexes/
// skill-prereqs.json — a hand-authored file, deliberately NOT inside
// grammar-index.json, which is machine-regenerated by
// scripts/build_grammar_index.py and would silently discard anything added
// there).
//
// engine/recommend.js's weakestSkill()/weakestWords() were the first, narrow
// slice of this (recycle/srs evidence only, binary weak-or-null) and have
// moved here as weakSkills()/weakWords() — recommend.js now calls into this
// module instead of computing its own signal, same migration pattern step 1
// used for unitFor()/lastCompletedLessonId().

const LearnerModel = (function () {
    'use strict';

    // Skills/words with fewer reviews than this don't carry enough signal
    // to call "weak" rather than "barely seen yet" — moved here verbatim
    // from engine/recommend.js.
    const MIN_REVIEWED = 2;
    const MIN_REVIEWED_WORDS = 3;
    const WEAK_WORDS_LIMIT = 8;

    // Ease-classification cutoffs, derived from engine/srs.js's SRS_CONFIG
    // (START_EASE 2.5, range 1.3-3.0). 2.0 takes real sustained struggle to
    // reach from the starting point; 2.6 requires having climbed above it
    // at least once via an "easy" rating — real demonstrated ease, not just
    // "hasn't been rated down yet."
    const WEAK_EASE_CEILING = 2.0;
    const STRONG_EASE_FLOOR = 2.6;

    const STATES = ['not-yet-seen', 'weak', 'developing', 'strong'];

    function classifyEase(avgEase) {
        if (avgEase < WEAK_EASE_CEILING) return 'weak';
        if (avgEase < STRONG_EASE_FLOOR) return 'developing';
        return 'strong';
    }

    // One tier down, floored at 'weak' — used when a level-test miss
    // contradicts otherwise-solid recycle evidence. A single test miss is
    // real but partial evidence (one question, no repeat-testing, no
    // magnitude): it shouldn't unilaterally overrule months of recycle
    // history by nuking straight to 'weak', but it shouldn't be silently
    // ignored either.
    // A card with review history — including one that has only ever been
    // missed: 'again' resets `reviews` to 0 (engine/srs.js, engine/
    // recycle.js), so counting `reviews` alone made a pure miss look
    // exactly like "never seen" and hid the weakest items of all.
    function hasHistory(card) {
        return !!card && (card.reviews > 0 || card.lapses > 0);
    }

    function downgrade(state) {
        const i = STATES.indexOf(state);
        return STATES[Math.max(1, i - 1)]; // never below 'weak' (index 1)
    }

    async function _grammarIndex() {
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return null;
        try {
            return await Content.json(Lang.content('indexes/grammar-index.json'));
        } catch (error) {
            return null;
        }
    }

    // The Grammar Driller's own item bank (Spanish only today). Its items
    // aren't in grammar-index.json, so the driller records them in the
    // recycle schedule as "bank:<id>" and they're joined back here.
    async function _grammarBank() {
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return null;
        try {
            return await Content.json(Lang.content('drills/grammar/a1-bank.json'));
        } catch (error) {
            return null;
        }
    }

    // skillId -> [{ id }] of every recycle-schedule id that is evidence for
    // it: grammar-index.json's lesson exercises plus the bank items whose
    // module maps to that skill (same underscore->hyphen rule the Grammar
    // Driller's _lessonSkillFor() uses). null when neither source loads.
    async function _skillRefs() {
        const [index, bank] = await Promise.all([_grammarIndex(), _grammarBank()]);
        if (!index && !bank) return null;
        const bySkill = Object.assign({}, (index && index.bySkill) || {});
        const copied = new Set();
        ((bank && bank.items) || []).forEach(item => {
            if (!item || !item.id || !item.module) return;
            const hyphenated = item.module.replace(/_/g, '-');
            const skillId = (bySkill[hyphenated] || !bySkill[item.module]) ? hyphenated : item.module;
            if (!copied.has(skillId)) {
                bySkill[skillId] = (bySkill[skillId] || []).slice();
                copied.add(skillId);
            }
            bySkill[skillId].push({ id: 'bank:' + item.id });
        });
        return bySkill;
    }

    // Cached per course after first fetch — a hand-authored file that
    // rarely changes, unlike the schedules this module reads live. Missing
    // or unparsable degrades to {}, same defensive pattern
    // loadRecycleSchedule() (engine/recycle.js) already uses, so an absent
    // or half-authored prereqs file is silent, not a crash.
    let _prereqsCache = null;
    let _prereqsCacheCourse = null;

    async function _prereqs() {
        const course = (typeof Lang !== 'undefined') ? Lang.key('') : '';
        if (_prereqsCache && _prereqsCacheCourse === course) return _prereqsCache;
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return {};
        try {
            _prereqsCache = await Content.json(Lang.content('indexes/skill-prereqs.json'));
        } catch (error) {
            _prereqsCache = {};
        }
        _prereqsCacheCourse = course;
        return _prereqsCache;
    }

    // ----------------------------------------
    // GRAMMAR SKILLS
    // ----------------------------------------

    // Every stored level-test result's weakest[] list, flattened into one
    // Set of flagged skill ids — checked as a boolean vote per skill (the
    // stored result already discards per-topic magnitude, so this can't be
    // more than a flag).
    function _levelTestFlags() {
        const flags = new Set();
        if (typeof LevelTest === 'undefined' || typeof LEVEL_ORDER === 'undefined') return flags;
        LEVEL_ORDER.forEach(level => {
            const result = LevelTest.resultFor(level);
            (result && result.weakest || []).forEach(id => flags.add(id));
        });
        return flags;
    }

    // The full classification for one grammar skill, folding recycle-
    // schedule evidence (exercise-level ease, joined via grammar-index.json)
    // with the level-test vote. See the module header for the shape of each
    // evidence source and the file's own comments below for the combining
    // rule.
    async function skillState(skillId) {
        const bySkill = await _skillRefs();
        const schedule = (typeof loadRecycleSchedule === 'function') ? loadRecycleSchedule() : {};
        const refs = (bySkill && bySkill[skillId]) || [];

        let totalEase = 0, seen = 0;
        refs.forEach(entry => {
            const card = schedule[entry.id];
            if (hasHistory(card)) {
                seen++;
                totalEase += card.ease;
            }
        });

        const recycle = seen > 0 ? { seen, avgEase: totalEase / seen } : null;
        const levelTestFlagged = _levelTestFlags().has(skillId);

        let state;
        if (!recycle) {
            state = levelTestFlagged ? 'weak' : 'not-yet-seen';
        } else if (seen === 1) {
            state = levelTestFlagged ? 'weak' : 'developing';
        } else {
            const base = classifyEase(recycle.avgEase);
            state = levelTestFlagged ? downgrade(base) : base;
        }

        const production = productionState(skillId);
        const productionWeak = !!(production && production.state === 'weak');

        return { skillId, state, recycle, levelTestFlagged, production, productionWeak };
    }

    // The skills with real trouble signal, worst first — replaces
    // engine/recommend.js's weakestSkill(), returning the full classified
    // shape (a strict superset: skillId/state/recycle/levelTestFlagged)
    // rather than a bare skill-id string. A skill only appears here once it
    // clears the same MIN_REVIEWED floor weakestSkill() always required, OR
    // is level-test-flagged with no recycle history at all — surfacing that
    // is the actual gap this module closes; today's code silently drops a
    // level-test miss unless recycle evidence also happens to exist.
    async function weakSkills(limit) {
        const bySkill = await _skillRefs();
        if (!bySkill) return [];
        const schedule = (typeof loadRecycleSchedule === 'function') ? loadRecycleSchedule() : {};
        const flags = _levelTestFlags();

        const results = [];
        Object.keys(bySkill).forEach(skillId => {
            const refs = bySkill[skillId] || [];
            let totalEase = 0, seen = 0;
            refs.forEach(entry => {
                const card = schedule[entry.id];
                if (hasHistory(card)) {
                    seen++;
                    totalEase += card.ease;
                }
            });

            const levelTestFlagged = flags.has(skillId);
            const recycle = seen > 0 ? { seen, avgEase: totalEase / seen } : null;

            let state = null;
            if (!recycle && levelTestFlagged) {
                state = 'weak';
            } else if (recycle && seen >= MIN_REVIEWED) {
                const base = classifyEase(recycle.avgEase);
                state = levelTestFlagged ? downgrade(base) : base;
            }
            // seen === 1 (underpowered) and unflagged recycle-only cases
            // are deliberately excluded from this ranked list, same honesty
            // rule weakestSkill() always applied — "developing on one data
            // point" isn't a confident enough signal to actively recommend
            // practising.

            if (state === 'weak' || state === 'developing') {
                results.push({ skillId, state, recycle, levelTestFlagged });
            }
        });

        // Weak before developing; within a tier, lower ease (or, for a
        // level-test-only flag with no recycle data, treated as worst)
        // sorts first.
        const rank = s => (s.state === 'weak' ? 0 : 1);
        const ease = s => (s.recycle ? s.recycle.avgEase : -1);
        results.sort((a, b) => rank(a) - rank(b) || ease(a) - ease(b));

        return results.slice(0, limit || results.length);
    }

    // ----------------------------------------
    // VOCABULARY
    // ----------------------------------------

    // The classification for one lemma, folding srsDeck (active review) and
    // knownWords (graduated or manually declared). Sync, unlike skillState —
    // both stores are plain in-memory globals kept live by engine/srs.js,
    // same as engine/recommend.js's weakestWords() already assumed.
    function wordState(lemma) {
        if (typeof knownWords !== 'undefined' && Array.isArray(knownWords)) {
            const known = knownWords.find(w => w.spanish === lemma);
            if (known) {
                return {
                    lemma,
                    state: 'strong',
                    verified: !!known.graduated,
                    source: known.graduated ? 'graduated' : 'known'
                };
            }
        }

        if (typeof srsDeck !== 'undefined' && Array.isArray(srsDeck)) {
            const card = srsDeck.find(c => c.spanish === lemma);
            if (card) {
                if (!hasHistory(card)) {
                    return { lemma, state: 'not-yet-seen', verified: false, source: 'srs', ease: card.ease, reviews: 0 };
                }
                let state = classifyEase(card.ease);
                // Fewer than MIN_REVIEWED_WORDS caps the ceiling at
                // 'developing' — not enough repeats to call it 'strong'
                // yet — but does not raise a genuinely low ease, since one
                // bad rating is still real trouble signal.
                if (card.reviews < MIN_REVIEWED_WORDS && state === 'strong') state = 'developing';
                return { lemma, state, verified: false, source: 'srs', ease: card.ease, reviews: card.reviews };
            }
        }

        return { lemma, state: 'not-yet-seen', verified: false, source: 'srs' };
    }

    // The words with the worst average ease among those with real review
    // history — replaces engine/recommend.js's weakestWords(), same honesty
    // rule (returns [] below the review-count floor) but keeps ease/reviews
    // in the returned shape alongside the lemma/translation/pos every
    // caller already expects.
    //
    // After those, words the learner keeps looking up in the Reader without
    // ever taking them on (see recordLookup()) — a word tapped on
    // LOOKUP_WEAK_DAYS separate days is plainly not known, card or no card.
    function weakWords(limit) {
        if (typeof srsDeck === 'undefined' || !Array.isArray(srsDeck)) return [];
        const max = limit || WEAK_WORDS_LIMIT;

        const reviewed = srsDeck.filter(card => hasHistory(card) && typeof card.ease === 'number');
        const fromSrs = reviewed.length < MIN_REVIEWED_WORDS ? [] : reviewed
            .slice()
            // Ease is the primary sort, but several cards pile up at
            // SRS_CONFIG.MIN_EASE once they've had a bad run — among those
            // ties, a card with more lapses (engine/srs.js's card.lapses)
            // is the more predictively weak one, so it sorts first.
            .sort((a, b) => (a.ease - b.ease) || ((b.lapses || 0) - (a.lapses || 0)))
            .slice(0, max)
            .map(card => ({
                lemma: card.spanish,
                translation: card.english,
                pos: card.type,
                ease: card.ease,
                reviews: card.reviews,
                leech: !!card.leech
            }));

        return fromSrs.concat(lookedUpWords()).slice(0, max);
    }

    // ----------------------------------------
    // READER LOOKUPS
    // ----------------------------------------
    // Tapping a word in the Reader to see what it means is the plainest
    // "I don't know this" the app gets. Called from showWord() (engine/
    // reader.js) with the resolved lemma. Two effects:
    //   - a word with an SRS card counts as a missed review ('again' via
    //     creditPractice()), at most once per word per day, so re-opening
    //     the same popup or meeting the word twice in one text isn't
    //     punished twice;
    //   - every lookup is logged by day, so a word looked up again and
    //     again without ever being added still surfaces in weakWords().
    // Known words (My Dictionary) are skipped — looking one up to hear it
    // or check a nuance isn't evidence it's been forgotten.
    const LOOKUP_WEAK_DAYS = 2;
    const LOOKUP_DAYS_KEPT = 10;

    function _lookupKey() {
        return (typeof Lang !== 'undefined') ? Lang.key('wordLookups') : 'wordLookups';
    }

    function _loadLookups() {
        try {
            return JSON.parse(localStorage.getItem(_lookupKey()) || '{}');
        } catch (e) {
            return {};
        }
    }

    function recordLookup(lemma, translation, pos) {
        if (!lemma) return;
        if (typeof isKnown === 'function' && isKnown(lemma)) return;
        const today = new Date().toISOString().slice(0, 10);
        const lookups = _loadLookups();
        const entry = lookups[lemma] || { days: [], count: 0 };
        const firstToday = entry.days.indexOf(today) === -1;
        entry.count++;
        if (firstToday) entry.days = entry.days.concat(today).slice(-LOOKUP_DAYS_KEPT);
        if (translation) entry.translation = translation;
        if (pos) entry.pos = pos;
        lookups[lemma] = entry;
        try {
            localStorage.setItem(_lookupKey(), JSON.stringify(lookups));
        } catch (e) {}

        if (firstToday && typeof creditPractice === 'function') {
            creditPractice([{ lemma, rating: 'again' }]);
        }
    }

    // Words looked up on LOOKUP_WEAK_DAYS+ separate days that have no SRS
    // card and aren't known — most-looked-up first.
    function lookedUpWords() {
        const lookups = _loadLookups();
        const carded = new Set((typeof srsDeck !== 'undefined' && Array.isArray(srsDeck)) ? srsDeck.map(c => c.spanish) : []);
        return Object.keys(lookups)
            .filter(lemma => lookups[lemma].days.length >= LOOKUP_WEAK_DAYS)
            .filter(lemma => !carded.has(lemma) && !(typeof isKnown === 'function' && isKnown(lemma)))
            .sort((a, b) => (lookups[b].days.length - lookups[a].days.length) || (lookups[b].count - lookups[a].count))
            .map(lemma => ({
                lemma,
                translation: lookups[lemma].translation || '',
                pos: lookups[lemma].pos || 'unknown',
                ease: null,
                reviews: 0,
                leech: false,
                lookups: lookups[lemma].days.length
            }));
    }

    // ----------------------------------------
    // DRILLERS (moved from engine/recommendationEngine.js)
    // ----------------------------------------
    // Every driller lacking a real competence signal today, mapped to the
    // curriculum lesson that gates its relevance — populated only where a
    // driller's own source comments state a real milestone, not fabricated
    // for the rest. Grammar and Vocabulary aren't listed here: they already
    // have this module's richer SM-2-based signal above. Belongs here, not
    // in RecommendationEngine, for the same reason weakSkills()/weakWords()
    // do: this module tracks what's weak, RecommendationEngine only ranks
    // and presents what this module already found. Uses engine/drillHistory.js's
    // accuracy-% classification as-is (not reconciled onto this module's
    // SM-2 ease scale — a deliberate step-3 decision, since the two measure
    // different things), so this only unifies where the answer to "is the
    // learner weak at X" comes from, not the underlying number scale.
    const DRILLER_UNLOCK = {
        'hu-suffix': 'lesson.a1.22',      // matches hu-suffix.js's own "Unit 5" (plural) comment
        'hu-prefix': 'lesson.a2.01',      // driller's own comment: full prefix system is an A2 topic
        'hu-morphology': 'lesson.a1.51'   // matches hu-suffix.js's "Unit 11+" (case) comment
        // hu-verb, verbs, translation, listening: no gate — none of these
        // four's own header comments state a curriculum-scoping rationale;
        // relevance for them is accuracy-history only.
    };

    const DRILLER_TITLES = {
        verbs: 'Verb Driller',
        translation: 'Translation Driller',
        listening: 'Listening Driller',
        speaking: 'Speaking Driller',
        'hu-suffix': 'Suffix Driller',
        'hu-prefix': 'Prefix Driller',
        'hu-morphology': 'Morphology Driller',
        'hu-verb': 'Verb Driller'
    };

    const TRACKED_DRILLERS = Object.keys(DRILLER_TITLES);

    // Mirrors workshop.js's own DRILLERS[].langs / _available() filter —
    // `verbs` is Spanish-only, the hu-* drillers are Hungarian-only.
    function _drillerAvailable(id) {
        if (id === 'verbs') return (typeof Lang !== 'undefined') && Lang.code().startsWith('es');
        if (id.indexOf('hu-') === 0) return (typeof Lang !== 'undefined') && Lang.code() === 'hu';
        return true;
    }

    function _drillerUnlocked(id) {
        const anchor = DRILLER_UNLOCK[id];
        if (!anchor) return true;
        return (typeof LearnerPath !== 'undefined') ? LearnerPath.isComplete(anchor) : true;
    }

    // A driller becomes eligible once BOTH curriculum-unlocked (or ungated)
    // AND its accuracy history classifies weak — unlocked-but-never-tried
    // stays silent, consistent with weakSkills()'s own underpowered-data
    // rule above.
    function weakDrillers() {
        const candidates = [];
        TRACKED_DRILLERS.forEach(id => {
            if (!_drillerAvailable(id) || !_drillerUnlocked(id)) return;
            const cls = (typeof DrillHistory !== 'undefined') ? DrillHistory.classify(id) : { state: null };
            if (cls.state === 'weak') {
                candidates.push({ drillerId: id, title: DRILLER_TITLES[id], avgAccuracy: cls.avgAccuracy });
            }
        });
        return candidates;
    }

    // Every tracked driller the learner can use right now (right language,
    // curriculum-unlocked), with its accuracy classification, weak or not —
    // StudyPlan ranks the weak ones and uses the rest as filler.
    function availableDrillers() {
        return TRACKED_DRILLERS
            .filter(id => _drillerAvailable(id) && _drillerUnlocked(id))
            .map(id => {
                const cls = (typeof DrillHistory !== 'undefined') ? DrillHistory.classify(id) : { state: null };
                return { drillerId: id, title: DRILLER_TITLES[id], state: cls.state, avgAccuracy: cls.avgAccuracy };
            });
    }

    // ----------------------------------------
    // ORAL PRODUCTION EVIDENCE (Speaking Driller & Lesson Speaking)
    // ----------------------------------------
    // Tracks oral recall and spoken production per skill.
    // Unlike written recognition exercises (graded on SM-2 ease via recycleSchedule),
    // oral production measures whether the learner can retrieve and pronounce
    // the structure out loud when prompted.
    //
    // Honesty principles:
    // - A single speaking miss NEVER downgrades an established written skill card.
    // - Requires >= 2 spoken attempts before classifying as weak (<60%) or strong (>=80%).
    // - Surfaced via productionState(skillId) and weakProductionSkills() to identify
    //   where written recognition is ahead of oral recall.

    function _productionKey() {
        return (typeof Lang !== 'undefined') ? Lang.key('productionEvidence') : 'productionEvidence';
    }

    function _loadProduction() {
        try {
            return JSON.parse(localStorage.getItem(_productionKey()) || '{}');
        } catch (e) {
            return {};
        }
    }

    function _saveProduction(data) {
        try {
            localStorage.setItem(_productionKey(), JSON.stringify(data));
        } catch (e) {}
    }

    function _assessmentKey() {
        return (typeof Lang !== 'undefined') ? Lang.key('assessmentHistory') : 'assessmentHistory';
    }

    function _loadAssessments() {
        try {
            return JSON.parse(localStorage.getItem(_assessmentKey()) || '[]');
        } catch (e) {
            return [];
        }
    }

    function _saveAssessments(list) {
        try {
            localStorage.setItem(_assessmentKey(), JSON.stringify(list.slice(0, 20)));
        } catch (e) {}
    }

    function recordProduction(skillIds, isCorrect, accuracy, modality) {
        if (!skillIds) return;
        const list = Array.isArray(skillIds) ? skillIds : [skillIds];
        if (!list.length) return;

        const store = _loadProduction();
        const score = typeof accuracy === 'number' ? Math.max(0, Math.min(100, Math.round(accuracy))) : (isCorrect ? 100 : 0);
        const modKey = (modality === 'written' || modality === 'written-production') ? 'written' : 'oral';
        let changed = false;

        list.forEach(skillId => {
            if (!skillId) return;
            const entry = store[skillId] || {
                attempts: 0,
                correct: 0,
                avgAccuracy: 0,
                lastSeen: null,
                modalities: {
                    oral: { attempts: 0, correct: 0, avgAccuracy: 0, lastSeen: null },
                    written: { attempts: 0, correct: 0, avgAccuracy: 0, lastSeen: null }
                }
            };
            if (!entry.modalities) {
                entry.modalities = {
                    oral: { attempts: entry.attempts, correct: entry.correct, avgAccuracy: entry.avgAccuracy, lastSeen: entry.lastSeen },
                    written: { attempts: 0, correct: 0, avgAccuracy: 0, lastSeen: null }
                };
            }

            // Aggregate stats
            entry.attempts++;
            if (isCorrect) entry.correct++;
            entry.avgAccuracy = Math.round(((entry.avgAccuracy * (entry.attempts - 1)) + score) / entry.attempts);
            entry.lastSeen = new Date().toISOString();

            // Modality-specific stats
            const mEntry = entry.modalities[modKey] || (entry.modalities[modKey] = { attempts: 0, correct: 0, avgAccuracy: 0, lastSeen: null });
            mEntry.attempts++;
            if (isCorrect) mEntry.correct++;
            mEntry.avgAccuracy = Math.round(((mEntry.avgAccuracy * (mEntry.attempts - 1)) + score) / mEntry.attempts);
            mEntry.lastSeen = entry.lastSeen;

            store[skillId] = entry;
            changed = true;
        });

        if (changed) {
            _saveProduction(store);
        }
    }

    /**
     * Ingests a structured assessment from GraderEngine into the Learner Model.
     * Maps demonstrated skills (positive evidence) and weak skills/errors (formative negative evidence)
     * using canonical Parlour skill IDs.
     */
    function recordAssessment(assessment, context) {
        if (!assessment || typeof assessment !== 'object') return;
        const ctx = context || {};
        const modality = (ctx.modality === 'oral' || ctx.modality === 'oral-production' || ctx.isSpeaking) ? 'oral' : 'written';

        // 1. Demonstrated skills -> positive production evidence
        if (Array.isArray(assessment.demonstratedSkills)) {
            assessment.demonstratedSkills.forEach(item => {
                const sId = typeof item === 'string' ? item : item.skillId;
                if (!sId) return;
                const conf = (item && typeof item.confidence === 'number') ? item.confidence : 0.85;
                const acc = Math.round(conf * 100);
                recordProduction(sId, true, acc, modality);
            });
        }

        // 2. Weak skills -> formative weakness evidence
        if (Array.isArray(assessment.weakSkills)) {
            assessment.weakSkills.forEach(item => {
                const sId = typeof item === 'string' ? item : item.skillId;
                if (!sId) return;
                const grammarDim = assessment.dimensions ? assessment.dimensions.grammar : 0.5;
                const acc = Math.round(grammarDim * 100);
                recordProduction(sId, false, acc, modality);
            });
        }

        // 3. Concrete errors mapped to skill IDs
        if (Array.isArray(assessment.errors)) {
            assessment.errors.forEach(err => {
                if (!err || !err.skillId) return;
                const penalty = err.severity === 'major' ? 30 : 50;
                recordProduction(err.skillId, false, penalty, modality);
            });
        }

        // 4. Save assessment history snapshot (retaining last 20)
        const history = _loadAssessments();
        const snapshot = {
            id: 'assm_' + Date.now(),
            timestamp: new Date().toISOString(),
            overallScore: assessment.overallScore,
            taskCompletion: assessment.taskCompletion,
            dimensions: assessment.dimensions,
            modality,
            cefrLevel: ctx.cefrLevel || assessment.cefrLevel || 'B2',
            taskType: ctx.taskType || 'extended_production',
            title: ctx.title || ctx.promptTitle || 'Writing Production',
            errorsCount: (assessment.errors || []).length,
            demonstratedCount: (assessment.demonstratedSkills || []).length,
            weakCount: (assessment.weakSkills || []).length,
            localStats: assessment.localStats || null
        };
        history.unshift(snapshot);
        _saveAssessments(history);

        return snapshot;
    }

    function assessmentHistory(limit) {
        const list = _loadAssessments();
        return typeof limit === 'number' ? list.slice(0, limit) : list;
    }

    function productionState(skillId) {
        if (!skillId) return null;
        const store = _loadProduction();
        const entry = store[skillId];
        if (!entry || !entry.attempts) return null;

        function calcState(attempts, avgAccuracy) {
            if (!attempts || attempts < 2) return 'underpowered';
            if (avgAccuracy < 60) return 'weak';
            if (avgAccuracy < 80) return 'developing';
            return 'strong';
        }

        const state = calcState(entry.attempts, entry.avgAccuracy);
        const oralState = entry.modalities && entry.modalities.oral
            ? calcState(entry.modalities.oral.attempts, entry.modalities.oral.avgAccuracy)
            : 'not-yet-seen';
        const writtenState = entry.modalities && entry.modalities.written
            ? calcState(entry.modalities.written.attempts, entry.modalities.written.avgAccuracy)
            : 'not-yet-seen';

        return {
            skillId,
            attempts: entry.attempts,
            correct: entry.correct,
            avgAccuracy: entry.avgAccuracy,
            accuracy: entry.avgAccuracy,
            lastSeen: entry.lastSeen,
            state,
            modalities: entry.modalities || {
                oral: { attempts: entry.attempts, correct: entry.correct, avgAccuracy: entry.avgAccuracy, lastSeen: entry.lastSeen },
                written: { attempts: 0, correct: 0, avgAccuracy: 0, lastSeen: null }
            },
            oralState,
            writtenState
        };
    }

    async function weakProductionSkills(limit, modality) {
        const store = _loadProduction();
        const candidates = [];
        const targetMod = (modality === 'written' || modality === 'oral') ? modality : null;

        for (const skillId of Object.keys(store)) {
            const entry = store[skillId];
            if (!entry) continue;

            if (targetMod && entry.modalities && entry.modalities[targetMod]) {
                const m = entry.modalities[targetMod];
                if (m.attempts < 2 || m.avgAccuracy >= 60) continue;
                candidates.push({
                    skillId,
                    attempts: m.attempts,
                    correct: m.correct,
                    avgAccuracy: m.avgAccuracy,
                    lastSeen: m.lastSeen,
                    modality: targetMod,
                    state: 'weak'
                });
            } else {
                if (entry.attempts < 2 || entry.avgAccuracy >= 60) continue;
                candidates.push({
                    skillId,
                    attempts: entry.attempts,
                    correct: entry.correct,
                    avgAccuracy: entry.avgAccuracy,
                    lastSeen: entry.lastSeen,
                    state: 'weak'
                });
            }
        }

        candidates.sort((a, b) => a.avgAccuracy - b.avgAccuracy);
        return candidates.slice(0, limit || candidates.length);
    }

    /**
     * Rolls every skill's per-modality production evidence into one number,
     * for a screen that wants "how is the learner doing at X overall" rather
     * than a skill-by-skill breakdown. Weighted by attempts, so one skill
     * drilled 20 times doesn't get diluted by ten skills tried once each.
     * Returns null when there's no evidence yet - callers should show an
     * honest "not measured yet" rather than a misleading 0%.
     */
    function productionSummary(modality) {
        const store = _loadProduction();
        const targetMod = (modality === 'written' || modality === 'oral') ? modality : null;
        let attempts = 0, correct = 0, weightedAccuracy = 0, lastSeen = null;

        Object.keys(store).forEach(skillId => {
            const entry = store[skillId];
            if (!entry) return;
            const source = (targetMod && entry.modalities && entry.modalities[targetMod])
                ? entry.modalities[targetMod]
                : (targetMod ? null : entry);
            if (!source || !source.attempts) return;
            attempts += source.attempts;
            correct += source.correct;
            weightedAccuracy += source.avgAccuracy * source.attempts;
            if (!lastSeen || (source.lastSeen && source.lastSeen > lastSeen)) lastSeen = source.lastSeen;
        });

        if (!attempts) return null;
        return {
            attempts,
            correct,
            avgAccuracy: Math.round(weightedAccuracy / attempts),
            lastSeen
        };
    }

    // ----------------------------------------
    // PREREQUISITES
    // ----------------------------------------

    // Cached synchronously after the first async load — callers that need
    // this synchronously (rendering) should have already triggered a
    // isReady()/prerequisitesFor() call once during page load. Returns []
    // before the first successful fetch, same graceful-empty behaviour as
    // an absent file.
    function prerequisitesFor(skillId) {
        const data = _prereqsCache || {};
        return data[skillId] || [];
    }

    // Advisory, not a mastery gate — matching LevelTest's own stated
    // "advisory, not a gate" philosophy and the roadmap's framing of this
    // whole model as "mostly hidden from the learner." A prerequisite
    // counts as met once the learner has been introduced to it at all
    // (anything but not-yet-seen), not once it's specifically "strong."
    async function isReady(skillId) {
        await _prereqs(); // ensure the cache is populated for prerequisitesFor()
        const prereqIds = prerequisitesFor(skillId);
        if (!prereqIds.length) return { ready: true, missing: [] };

        const missing = [];
        for (const id of prereqIds) {
            const state = await skillState(id);
            if (state.state === 'not-yet-seen') missing.push(id);
        }
        return { ready: missing.length === 0, missing };
    }

    // ----------------------------------------
    // CEFR CAN-DO COMPETENCIES & METACOGNITIVE CALIBRATION
    // ----------------------------------------
    // Tracks self-efficacy ("I can...") vs objective exercise performance.
    // Classifies each competency into four pedagogical states:
    // 1. 'verified' (Verified Mastery): checked === true && accuracy >= 75%
    // 2. 'confidence-gap': checked === false && accuracy >= 75%
    // 3. 'blindspot': checked === true && accuracy < 75%
    // 4. 'deficit': checked === false && accuracy < 75%
    // In addition, if verified > 30 days ago with no recent practice, it is flagged as 'decayed'.

    let _competenciesIndexCache = null;
    let _competenciesIndexCourse = null;

    async function loadCompetenciesIndex() {
        const course = (typeof Lang !== 'undefined') ? Lang.key('') : '';
        if (_competenciesIndexCache && _competenciesIndexCourse === course) {
            return _competenciesIndexCache;
        }
        if (typeof Content === 'undefined' || typeof Lang === 'undefined') return [];
        try {
            _competenciesIndexCache = await Content.json(Lang.content('indexes/competencies-index.json')) || [];
        } catch (e) {
            _competenciesIndexCache = [];
        }
        _competenciesIndexCourse = course;
        return _competenciesIndexCache;
    }

    function _competencyKey() {
        return (typeof Lang !== 'undefined') ? Lang.key('competencyRecords') : 'competencyRecords';
    }

    function _loadCompetencies() {
        try {
            return JSON.parse(localStorage.getItem(_competencyKey()) || '{}');
        } catch (e) {
            return {};
        }
    }

    function _saveCompetencies(data) {
        try {
            localStorage.setItem(_competencyKey(), JSON.stringify(data));
        } catch (e) {}
    }

    /**
     * Records checklist competencies evaluated at the end of a lesson.
     * items: Array of { text: string, checked: boolean, exerciseAccuracy: number }
     */
    function recordCompetencies(lessonId, items) {
        if (!lessonId || !Array.isArray(items) || !items.length) return;
        const store = _loadCompetencies();
        const now = Date.now();

        items.forEach(item => {
            if (!item || !item.text) return;
            const text = item.text.trim();
            const checked = !!item.checked;
            const accuracy = typeof item.exerciseAccuracy === 'number' ? item.exerciseAccuracy : 100;

            const existing = store[text] || {};

            let state;
            if (existing.state === 'verified' && checked) {
                state = 'verified';
            } else if (checked && accuracy >= 75) {
                state = 'verified';
            } else if (!checked && accuracy >= 75) {
                state = 'confidence-gap';
            } else if (checked && accuracy < 75) {
                state = 'blindspot';
            } else {
                state = 'deficit';
            }

            store[text] = {
                ...existing,
                text,
                lessonId: lessonId || existing.lessonId,
                checked,
                exerciseAccuracy: accuracy,
                state,
                timestamp: now,
                verifiedAt: state === 'verified' ? (existing.verifiedAt || now) : null,
                source: existing.source || 'lesson-checklist'
            };
        });

        _saveCompetencies(store);
    }

    /**
     * Verifies a competency statement (e.g. from Writing or Speaking Studio when score >= 75)
     */
    function verifyCompetency(textOrId, score, source, modality) {
        if (!textOrId) return;
        const store = _loadCompetencies();
        const now = Date.now();
        const text = textOrId.trim();

        const existing = store[text] || {};
        store[text] = {
            ...existing,
            text,
            checked: true,
            exerciseAccuracy: typeof score === 'number' ? Math.round(score) : (existing.exerciseAccuracy || 85),
            state: 'verified',
            verifiedAt: now,
            timestamp: now,
            modality: modality || existing.modality || 'oral',
            source: source || 'studio-assessment'
        };

        _saveCompetencies(store);
        return store[text];
    }

    function getCompetency(text) {
        if (!text) return null;
        const store = _loadCompetencies();
        const rec = store[text.trim()];
        if (!rec) return null;

        // Check 30-day decay for verified items
        if (rec.state === 'verified' && rec.verifiedAt) {
            const daysSince = (Date.now() - rec.verifiedAt) / (1000 * 60 * 60 * 24);
            if (daysSince > 30) {
                return { ...rec, state: 'decayed', isDecayed: true };
            }
        }
        return rec;
    }

    function allCompetencies() {
        return _loadCompetencies();
    }

    function competenciesForLesson(lessonId) {
        if (!lessonId) return [];
        const store = _loadCompetencies();
        const results = [];
        Object.keys(store).forEach(k => {
            if (store[k].lessonId === lessonId) {
                results.push(store[k]);
            }
        });
        return results;
    }

    /**
     * Returns unverified competencies for a given level or all levels.
     * Unverified includes: 'confidence-gap', 'blindspot', 'deficit', 'decayed', or unchecked items.
     */
    async function unverifiedCompetencies(level) {
        const index = await loadCompetenciesIndex();
        const store = _loadCompetencies();
        const now = Date.now();

        const filtered = level ? index.filter(c => (c.level || '').toUpperCase() === level.toUpperCase()) : index;
        const results = [];

        filtered.forEach(comp => {
            const rec = store[comp.text];
            if (!rec) {
                // Not yet evaluated or unchecked in lesson
                return;
            }
            if (rec.state === 'verified' && rec.verifiedAt) {
                const daysSince = (now - rec.verifiedAt) / (1000 * 60 * 60 * 24);
                if (daysSince > 30) {
                    results.push({ ...comp, ...rec, state: 'decayed', reason: 'Needs review (practiced > 30 days ago)' });
                }
            } else if (rec.state !== 'verified') {
                let reason = 'Needs practice';
                if (rec.state === 'confidence-gap') reason = 'Confidence gap (performed well, but felt uncertain)';
                else if (rec.state === 'blindspot') reason = 'Needs review (struggled during exercises)';
                else if (rec.state === 'deficit') reason = 'Immediate priority (struggled and left unchecked)';

                results.push({ ...comp, ...rec, reason });
            }
        });

        return results;
    }

    /**
     * Picks one can-do competency to use as a quick speaking prompt (Time-
     * Based Sessions' guaranteed speaking slot — see engine/studyPlan.js).
     * Prefers a genuinely unverified/weak one at the learner's level so the
     * prompt is actually useful practice, not busywork; falls back to any
     * competency from a lesson the learner has already completed (nothing
     * ahead of where they are), at that level first, any level if the
     * learner hasn't completed anything at this level yet. Returns null
     * when there's truly nothing appropriate yet (e.g. a brand-new learner
     * with zero completed lessons) — callers should skip the slot, not
     * invent a placeholder prompt.
     */
    async function pickSpeakingPrompt(level) {
        const unverified = await unverifiedCompetencies(level);
        if (unverified.length) {
            return unverified[Math.floor(Math.random() * unverified.length)];
        }

        const index = await loadCompetenciesIndex();
        const completed = (typeof isLessonComplete === 'function')
            ? index.filter(c => isLessonComplete(c.lessonId))
            : [];
        if (!completed.length) return null;

        const atLevel = level ? completed.filter(c => (c.level || '').toUpperCase() === level.toUpperCase()) : completed;
        const pool = atLevel.length ? atLevel : completed;
        return pool[Math.floor(Math.random() * pool.length)];
    }

    /**
     * Calculates competency statistics for a level:
     * { total, verified, confidenceGap, blindspot, deficit, decayed, upcoming, percent }
     */
    async function competencyStats(level) {
        const index = await loadCompetenciesIndex();
        const store = _loadCompetencies();
        const now = Date.now();

        const filtered = level ? index.filter(c => (c.level || '').toUpperCase() === level.toUpperCase()) : index;
        const total = filtered.length;

        let verified = 0, confidenceGap = 0, blindspot = 0, deficit = 0, decayed = 0, upcoming = 0;

        filtered.forEach(comp => {
            const rec = store[comp.text];
            if (!rec) {
                upcoming++;
            } else if (rec.state === 'verified') {
                const daysSince = rec.verifiedAt ? (now - rec.verifiedAt) / (1000 * 60 * 60 * 24) : 0;
                if (daysSince > 30) {
                    decayed++;
                } else {
                    verified++;
                }
            } else if (rec.state === 'confidence-gap') {
                confidenceGap++;
            } else if (rec.state === 'blindspot') {
                blindspot++;
            } else if (rec.state === 'deficit') {
                deficit++;
            } else {
                upcoming++;
            }
        });

        const percent = total > 0 ? Math.round((verified / total) * 100) : 0;

        return {
            total,
            verified,
            confidenceGap,
            blindspot,
            deficit,
            decayed,
            upcoming,
            unverified: total - verified,
            percent
        };
    }

    return {
        skillState,
        wordState,
        weakSkills,
        weakWords,
        recordLookup,
        lookedUpWords,
        weakDrillers,
        availableDrillers,
        prerequisitesFor,
        isReady,
        recordProduction,
        recordAssessment,
        productionState,
        weakProductionSkills,
        productionSummary,
        assessmentHistory,
        recordCompetencies,
        verifyCompetency,
        getCompetency,
        allCompetencies,
        competenciesForLesson,
        unverifiedCompetencies,
        pickSpeakingPrompt,
        competencyStats,
        loadCompetenciesIndex
    };
})();
