import type { Register } from 'claude-code'

// content/<lang>/<rest>, with the repo root in group 1
const CONTENT = /^(.*)\/content\/([^/]+)\/(.+\.json)$/

// Regenerated by build-manifest.py / the sync workflow (AGENTS.md); the four
// hand-maintained indexes are the exception.
const GENERATED =
  /^(curriculum\/curriculum|decks\/decks|stories\/manifest|lessons\/manifest)\.json$|^indexes\/(?!(skill-registry|grammar-titles|verb-tense-skills|skill-prereqs)\.json$)[^/]+\.json$/

// Runs validate_language() on just the one file, so the check takes seconds.
const VALIDATE = `
import importlib.util, pathlib, sys
s = importlib.util.spec_from_file_location('v', 'scripts/validate-content.py')
m = importlib.util.module_from_spec(s); s.loader.exec_module(m)
p = pathlib.Path(sys.argv[1]).resolve()
ok, bad, fails = m.validate_language(sys.argv[2], {p})
for f in fails: print(f)
sys.exit(1 if bad else 0)
`

function parse(filePath: string) {
  const m = CONTENT.exec(filePath.replace(/\\/g, '/'))
  return m && { root: m[1], lang: m[2], rest: m[3] }
}

async function guard($: any, e: { file_path: string }, next: (e: any) => Promise<any>) {
  const hit = parse(e.file_path)
  if (!hit || hit.rest.startsWith('schemas/')) return next(e)

  const isRepo = await $.fs.stat(`${hit.root}/scripts/validate-content.py`).then(() => true, () => false)
  if (!isRepo) return next(e)

  if (GENERATED.test(hit.rest))
    return {
      deny: `content-guard: content/${hit.lang}/${hit.rest} is generated by build-manifest.py and the sync workflow; a hand edit is overwritten on the next build. Fix the source content or the generator instead.`,
    }

  const ran = await next(e)
  if (ran.deny !== undefined || ran.isError) return ran

  const check = await $.process
    .run(['python', '-c', VALIDATE, e.file_path, hit.lang], { cwd: hit.root, timeoutMs: 60_000 })
    .catch(() => undefined)
  if (!check || check.exitCode === 0) return ran

  $.ui.toast(`content-guard: ${hit.rest} fails validation`)
  return {
    ...ran,
    context: [
      ...(ran.context ?? []),
      `content-guard: this file now fails validate-content.py. Fix it before writing more content (rules: AGENTS.md § "Exercise metadata"):\n${(check.stdout || check.stderr).trim().slice(0, 4000)}`,
    ],
  }
}

export const register: Register = on => {
  on('tool.call', { tool: 'Write' }, ($, e, next) => guard($, e, next))
  on('tool.call', { tool: 'Edit' }, ($, e, next) => guard($, e, next))
}
