#!/usr/bin/env python3
"""Teaching-order check for Hungarian content -- HU's counterpart to
audit-lesson.py's check_teaching_order(), not a full port of the whole
script. Flags an exercise that tests Hungarian never shown on its lesson's
grammar/vocabulary/story screens first.

Three real differences from the Spanish version, not just a find/replace:

1. Unit grouping. Spanish units are encoded in the filename itself
   (a1-01-01.json .. a1-01-consolidation.json). Hungarian A1/A2 lessons are
   flat-numbered (a1-01.json, a1-02.json, ...) with no unit grouping in the
   filename at all -- units only exist in `curriculum/curriculum.json`
   (generated by build-manifest.py), so this script reads unit/lesson
   grouping from there instead of parsing ids. B1 uses Spanish-style
   dash-part filenames (b1-01-01.json) and is grouped the same way for
   consistency, including its citizenship-track units (word-slug ids like
   b1-orszagma-01) -- curriculum.json already carries both tracks, unlike
   Spanish B1's Latin America track, which has no equivalent generated
   grouping at all.

2. Diacritics are not noise. Spanish's checker strips all accents before
   comparing tokens (a1-content-spec.md's normalise() does the same, and
   [[hungarian-accent-sensitive-grading]] memory already establishes why:
   Hungarian a/á, o/o"/ö and u/ú/ü are different letters, not accent
   variants of one letter. Stripping them would silently treat "haz" (not
   a real word) and "ház" (house) as the same token. This script lowercases
   only and keeps the full Hungarian alphabet.

3. Agglutination breaks literal substring matching far more than Spanish
   conjugation does. A lemma like "ház" surfaces in text as "házban",
   "házamban", "házak", etc. -- exact-match would flag nearly every content
   word as "never taught". Spanish already downgrades this to a warning for
   verbs; here it's the norm for most word classes, so `KnownWords.covers()`
   compares shared prefixes (a fixed-tolerance heuristic, not real
   morphological analysis -- the real HU stemmer lives in
   engine/hu-morphology.js, not ported here) instead of requiring an exact
   string match.

Not ported (needs its own design, not a mechanical port):
  - "5+ distinct exercise types", "I can" checklist phrasing, goals<->
    checklist 1:1 -- unverified whether HU content follows the same
    conventions as the Spanish guide docs these rules encode.
  - Consolidation shape -- HU consolidations use a Recognize/Recall/
    In Context/Produce structure, not Spanish's single "Review" group, so
    Spanish's consolidation-shape rule does not apply as-is.
  - Per-lesson title/word-count/exercise-count checks against a plan --
    curriculum.json actually carries `newWords`/`exercises` counts per
    lesson (real, generated plan data, better than what Spanish A1 has),
    but cross-checking them against actual lesson content is unbuilt.

    python scripts/audit-lesson-hu.py           # every level
    python scripts/audit-lesson-hu.py a1        # one level
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HU = ROOT / "content" / "hu"
CURRICULUM = HU / "curriculum" / "curriculum.json"

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

LEVELS = ("a1", "a2", "b1")
LEVEL_KEY = {"a1": "A1", "a2": "A2", "b1": "B1"}

HU_WORD = re.compile(r"[a-záéíóöőúüű]+")

# Character names and place/history names from the story world -- these
# don't need to be "taught" before use any more than Spanish content's own
# PROPER_NOUNS list in audit-lesson.py does. Built by scanning story text
# for capitalized mid-sentence words (2026-09-17); will need extending as
# new units introduce their own names. Base forms only -- matched by stem
# below, so an inflected form (Budapesten, Magyarországon) is caught too.
HU_PROPER_NOUNS = {
    "árpád", "meg", "magyarország", "szent", "istván", "kárpát", "duna",
    "anna", "budapest", "európa", "ilona", "korona", "közép", "pannónia",
    "tisza", "misi", "károly", "horvátország", "birodalom", "carlos",
    "kaganátus", "géza", "balaton", "jancsi", "kálmán", "jánosné",
    "andrás", "petra", "aranybulla", "avar", "alföld", "ukrajna",
    "szerbia", "dunántúl", "kossuth", "petőfi", "várhegy", "bécs",
    "gábor", "kovács", "fábián",
}


def read(path):
    return json.loads(path.read_text(encoding="utf-8"))


def same_stem(a, b):
    """True if a and b look like the same root with a different case/number
    suffix -- a stand-in for real morphological analysis (that lives in
    engine/hu-morphology.js, not ported here). Two heuristics: a short root
    (<4 chars, where an exact-length comparison would be too strict -- "ház"
    needs to match "házban") only has to be a prefix of the other word;
    anything longer needs to share all but a bounded tail (at most 3 chars,
    scaled down for shorter words so short unrelated words don't collide)."""
    short_len = min(len(a), len(b))
    if short_len < 4:
        return a.startswith(b) or b.startswith(a)
    common = 0
    for x, y in zip(a, b):
        if x != y:
            break
        common += 1
    allowed_tail = min(3, short_len // 3)
    return common >= short_len - allowed_tail


def hu_tokens(text):
    words = HU_WORD.findall((text or "").lower())
    # Strict startswith here, not the fuzzy same_stem() used elsewhere: a
    # proper noun only needs to match its own *inflected* forms (budapest ->
    # budapesten), which is always token = properNoun + suffix, so a plain
    # prefix check is both sufficient and correct. Using same_stem's
    # bounded-tolerance matching here was a real bug (found 2026-09-17):
    # "maga" (a common pronoun, "himself/herself") shares just enough of its
    # first few letters with "magyarország" that same_stem called them
    # related, silently deleting "maga" from every lesson's known-vocabulary
    # set -- meaning "magát" never resolved as known anywhere it was taught.
    #
    # Second bug, same shape, much bigger blast radius (found 2026-09-17):
    # plain startswith() has the identical problem for very short proper
    # nouns. "meg" (the protagonist's name, 3 chars) is also, coincidentally,
    # Hungarian's single most common verbal preverb -- "meg-" prefixes
    # hundreds of ordinary verbs (megyek, megnéz, meggyőz, megvesz...), all
    # of which silently vanished from every lesson's known-vocabulary set
    # for the entire session before this fix (318 distinct meg-prefixed
    # words found across the corpus). Hungarian case suffixes only ever
    # attach to the END of a name, never a prefix to the front, so
    # startswith(pn) is only meaningful for real proper-noun matching when
    # pn itself is long enough that a coincidental collision is implausible.
    # Every other entry in HU_PROPER_NOUNS is 4+ chars; "meg" is the only
    # 3-char one, so require exact equality for anything that short instead
    # of prefix matching.
    def is_proper_noun_form(word, pn):
        return word == pn if len(pn) < 4 else word.startswith(pn)

    return {w for w in words if not any(is_proper_noun_form(w, pn) for pn in HU_PROPER_NOUNS)}


def load_units(level):
    data = read(CURRICULUM)
    return data["levels"][LEVEL_KEY[level]]["units"]


def lesson_path(level, lesson_id):
    rest = lesson_id.split(f"lesson.{level}.", 1)[1]
    return HU / "lessons" / level / f"{level}-{rest}.json"


def load_exercises(lesson):
    refs = {s["ref"] for s in lesson.get("sections", []) if s["type"] == "exercise-group"}
    all_ex = {}
    for ref in refs:
        path = HU / ref
        if not path.exists():
            continue
        for ex in read(path).get("exercises", []):
            all_ex[ex["id"]] = ex
    return all_ex


def exercise_hungarian(ex):
    kind = ex.get("type")
    if kind == "matching":
        return [pair[0] for pair in ex.get("pairs", [])]
    if kind == "fill-blank":
        return [ex.get("sentence", "")] + (ex["answers"] if "answers" in ex else [ex.get("answer", "")])
    if kind == "sentence-builder":
        return ex.get("tiles", [])
    if kind == "dialogue-complete":
        return [line["text"] for line in ex.get("prompt", [])] + ex.get("options", [])
    if kind == "structured-writing":
        return [line["answer"] for line in ex.get("template", [])]
    if kind == "sentence-order":
        return ex.get("sentences", []) if ex.get("category") != "reading" else []
    if kind in ("listening-choice", "dictation"):
        return [ex.get("sentence", "")]
    if kind == "multiple-choice":
        # Unlike Spanish content, observed HU options are target-language
        # only (the English gloss lives in a separate "question" field), so
        # no language filter is needed here -- every option is required.
        return ex.get("options", [])
    return []


def teach_tokens(lesson, all_ex):
    for s in lesson.get("sections", []):
        kind = s["type"]
        if kind == "grammar":
            path = HU / s["ref"]
            if not path.exists():
                continue
            found = set()
            for part in read(path).get("sections", []):
                if part["type"] == "table":
                    for row in part.get("rows", []):
                        found |= hu_tokens(row[0])
                elif part["type"] == "examples":
                    for item in part.get("items", []):
                        # field is literally called "spanish" in HU content
                        # too -- schema/field naming wasn't renamed per
                        # language, it's just reused generically.
                        found |= hu_tokens(item.get("spanish", ""))
                elif part["type"] in ("text", "tip"):
                    found |= hu_tokens(part.get("content", ""))
            yield None, found, None
        elif kind == "vocabulary":
            path = HU / s["ref"]
            if path.exists():
                found = set()
                for word in read(path).get("words", []):
                    found |= hu_tokens(word["lemma"])
                yield None, found, None
        elif kind == "story":
            path = HU / s["ref"]
            if path.exists():
                found = set()
                for para in read(path).get("paragraphs", []):
                    if para.get("lang") == "en":
                        continue
                    found |= hu_tokens(para.get("text", ""))
                yield None, found, None
        elif kind == "exercise-group":
            for eid in s.get("exerciseRefs", []):
                ex = all_ex.get(eid)
                if not ex:
                    continue
                required = set()
                for text in exercise_hungarian(ex):
                    required |= hu_tokens(text)
                yield f"{s.get('title', '?')} / {eid}", set(), required


class KnownWords:
    """Words taught so far, bucketed by first-2-chars prefix so a fuzzy
    same_stem() lookup doesn't have to scan the whole vocabulary. 2 chars,
    not 3: a short root (e.g. "út", "hely") and its suffixed form ("útba")
    only reliably share that many characters -- bucketing by 3 silently
    missed every short-root match (their word[:3] bucket key differs from
    the suffixed form's, since the 3rd character is already suffix, not
    root) until this was caught 2026-09-17 auditing lesson.a1.60."""

    def __init__(self):
        self._buckets = {}

    def add(self, word):
        self._buckets.setdefault(word[:2], set()).add(word)

    def update(self, words):
        for w in words:
            self.add(w)

    def covers(self, token):
        if token in self._buckets.get(token[:2], ()):
            return True
        return any(same_stem(token, w) for w in self._buckets.get(token[:2], ()))


def accumulate_known(level):
    """Every word taught anywhere in a level, as a flat set -- used to seed
    a later level's walk (A2 assumes all of A1 is already known)."""
    known = set()
    for unit in load_units(level):
        for l in unit["lessons"]:
            path = lesson_path(level, l["id"])
            if not path.exists():
                continue
            lesson = read(path)
            all_ex = load_exercises(lesson)
            for label, introduced, required in teach_tokens(lesson, all_ex):
                known |= introduced
                if label is not None:
                    known |= required
    return known


def check_teaching_order(level):
    issues = []
    known = KnownWords()
    for earlier in LEVELS[:LEVELS.index(level)]:
        known.update(accumulate_known(earlier))

    for unit in load_units(level):
        for l in unit["lessons"]:
            if l["id"].endswith("-consolidation"):
                continue
            path = lesson_path(level, l["id"])
            if not path.exists():
                continue
            lesson = read(path)
            all_ex = load_exercises(lesson)
            for label, introduced, required in teach_tokens(lesson, all_ex):
                if label is None:
                    known.update(introduced)
                    continue
                unseen = sorted(t for t in required if not known.covers(t))
                if unseen:
                    issues.append(f"{l['id']} {label} needs: {', '.join(unseen)}")
                known.update(required)
    return issues


def main():
    requested = [a for a in sys.argv[1:] if a in LEVELS] or list(LEVELS)
    total = 0
    for level in LEVELS:
        if level not in requested:
            continue
        issues = check_teaching_order(level)
        total += len(issues)
        print(f"[{level}] {len(issues)} exercise(s) test untaught Hungarian")
        for issue in issues:
            print(f"  FAIL  {issue}")
        print()
    print(f"{total} exercise(s) test untaught Hungarian across {', '.join(requested)}")
    return 1 if total else 0


if __name__ == "__main__":
    sys.exit(main())
