#!/usr/bin/env python3
"""Generate each course's skill files from the language's source registry.

The source of truth is skills/<lang>.json (one registry per language: es-es and
es-latam share skills/es.json). This writes, for every course of that language:

    content/<course>/indexes/skill-registry.json   skills + retired slugs, as the app reads them
    content/<course>/indexes/grammar-titles.json   skill -> display title ("reading" for vocabulary)
    content/<course>/indexes/skill-prereqs.json    skill -> direct prerequisites (`requires`)

Never edit those three by hand; edit skills/<lang>.json and rerun this.

    python scripts/build_skill_registry.py           # write all languages
    python scripts/build_skill_registry.py --check   # exit 1 if any generated file is out of date

Format and rules: docs/skill-tagging-spec.md (ROADMAP 125).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
GENERATED = "Generated by scripts/build_skill_registry.py from skills/{lang}.json. Do not edit by hand."


def dump(obj):
    return json.dumps(obj, ensure_ascii=False, indent=1) + "\n"


def course_files(src):
    lang = src["language"]
    skills = src["skills"]
    retired = src.get("retired", {})
    registry = {"_comment": GENERATED.format(lang=lang) + " A retired slug is not a skill: it stays only until "
                "the read-through retags its exercises.",
                "language": lang,
                "skills": {**skills, **retired}}
    titles = {}
    for slug, s in {**skills, **retired}.items():
        titles[slug] = "reading" if s["kind"] == "vocabulary" else s["title"]
    prereqs = {"_comment": GENERATED.format(lang=lang) + " Direct prerequisites only (the `requires` field)."}
    for slug, s in skills.items():
        if s.get("requires"):
            prereqs[slug] = s["requires"]
    return {
        "indexes/skill-registry.json": dump(registry),
        "indexes/grammar-titles.json": dump(dict(sorted(titles.items()))),
        "indexes/skill-prereqs.json": dump(prereqs),
    }


def main():
    check = "--check" in sys.argv[1:]
    stale = []
    for path in sorted(SKILLS.glob("*.json")):
        if path.name == "families.json" or path.name.startswith("frozen-"):
            continue
        src = json.loads(path.read_text(encoding="utf-8"))
        files = course_files(src)
        for course in src["courses"]:
            for rel, text in files.items():
                out = ROOT / "content" / course / rel
                current = out.read_text(encoding="utf-8") if out.is_file() else None
                if current == text:
                    continue
                if check:
                    stale.append(out.relative_to(ROOT).as_posix())
                else:
                    out.write_text(text, encoding="utf-8", newline="\n")
                    print(f"wrote {out.relative_to(ROOT).as_posix()}")
    if check and stale:
        print("Out of date (run python scripts/build_skill_registry.py):")
        for s in stale:
            print(f"  {s}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
