#!/usr/bin/env python3
"""
Calibrator for Unit 10 stories to ensure all stories hit 680-760 words (target ~700, range 650-825).
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "content" / "es-latam"

cuba_01_paras = [
    "Asentada en una bahía de bolsa providencial que la convirtió en la 'Llave del Nuevo Mundo', La Habana despliega ante el viajero una de las tramas urbanas más deslumbrantes de América. Fundada en 1519 bajo una ceiba sagrada, la capital cubana creció como escala forzosa de las flotas de galeones cargados con la plata del Potosí y de Nueva España antes de cruzar el Atlántico hacia Sevilla. Para resguardar semejante tesoro frente a los piratas europeos, la corona española edificó un cinturón de fortalezas militares de piedra coralina que asombra por su solidez geométrica, encabezado por el castillo de los Tres Reyes del Morro y la fortaleza de San Carlos de la Cabaña.",
    "Adentrarse en La Habana Vieja, declarada Patrimonio de la Humanidad por la UNESCO en 1982, supone sumergirse en una sinfonía de estilos donde el barroco mudéjar, el neoclasicismo y el eclecticismo conviven con armonía. Sus cuatro plazas históricas articulan la vida civil: la plaza de Armas con el palacio de los Capitanes Generales; San Francisco frente al puerto; la plaza Vieja con sus aleros criollos; y la plaza de la Catedral, calificada por Alejo Carpentier como 'música convertida en piedra'. En estas casonas, los portales de arquería protegían del sol, mientras los célebres 'mediopuntos' —vitrales policromados en abanico— tamizaban la luz canicular en cascadas multicolores de azul y ámbar.",
    "Con el auge azucarero de inicios del siglo XX, la ciudad desbordó las murallas para expandirse a lo largo del Malecón, paseo marítimo de ocho kilómetros donde las olas rompen contra el muro de hormigón. En El Vedado florecieron mansiones y rascacielos Art Déco tan emblemáticos como el Edificio Bacardí, cuyas torres de terracota y bronce testimoniaban la prosperidad de los años treinta. Aunque décadas de bloqueo económico, salinidad marina y carestías materiales han deteriorado el fondo habitacional popular, los programas de restauración liderados por el historiador Eusebio Leal lograron rescatar cientos de palacios coloniales, convirtiendo la rehabilitación urbana en un modelo de autogestión comunitaria.",
    "A ciento sesenta kilómetros al occidente, en Pinar del Río, el paisaje cede su lugar a un prodigio geológico singular: el valle de Viñales. Enclavado en la cordillera de Guaniguanico, este valle cautiva por la presencia de los 'mogotes', formaciones rocosas kársticas de caliza que emergen verticalmente con alturas superiores a trescientos metros. Estas elevaciones de laderas abruptas y cúpulas redondeadas, vestigios de antiguas mesetas del Jurásico, albergan una flora fósil endémica extraordinariamente rara, entre la que descuella la 'palma corcho', considerada un fósil viviente botánico que sobrevivió a los dinosaurios conservando su morfología primitiva.",
    "Bajo la sombra de estos gigantes de caliza se extiende un mosaico rural de tierras rojas donde se cultiva el tabaco más codiciado del planeta. Los campesinos locales, conocidos como vegueros, han conservado métodos tradicionales: la tierra continúa roturándose con yuntas de bueyes para evitar la compactación mecánica que dañaría las raíces, mientras que las hojas se recolectan una a una con paciencia orfebre antes de trasladarse a las tradicionales 'casas de curado' de madera cubiertas con hojas de palma real, donde el aroma balsámico de la hoja en fermentación satura el aire cálido.",
    "El sistema cavernoso que horada estos mogotes añade otra dimensión de asombro histórico y geológico. Grutas como la Gran Caverna de Santo Tomás —la segunda red subterránea más extensa de América Latina con más de cuarenta y seis kilómetros explorados— y la Cueva del Indio resguardaron tanto los ritos de las poblaciones originarias guanajatabeyes como los refugios secretos de los esclavos 'cimarrones' que escapaban de las plantaciones durante la época colonial. Estas cavidades, por donde el río San Vicente discurre entre estalagmitas milenarias, conservan pictografías rupestres que testimonian la remota presencia humana en este santuario insular.",
    "La conjunción entre la monumentalidad arquitectónica de La Habana y la serenidad de Viñales define la dualidad primordial de Cuba: una cultura nacida del encuentro cosmopolita entre Europa, África y América que alzó palacios barrocos frente al mar, al tiempo que aprendió a labrar con devoción la tierra fértil de sus valles jurásicos. Esa síntesis perdura hoy como un testimonio indeleble donde la nobleza de la piedra labrada y la dignidad del trabajo rural se funden en un patrimonio de resonancia universal."
]

cuba_02_paras = [
    "Pocas figuras históricas encarnan con tanta pureza y dramatismo la conjunción entre la creación poética sublime y la acción revolucionaria intransigente como José Martí, proclamado por el pueblo cubano como el 'Apóstol' de su independencia nacional. Nacido en La Habana en 1853 en el seno de una familia española modesta, el joven Martí conoció muy temprano los rigores de la represión colonial: con apenas dieciséis años, tras redactar una carta donde acusaba de traidor a un condiscípulo alistado en el ejército realista durante la Guerra de los Diez Años, fue condenado a seis años de trabajos forzados en las canteras de cal viva de San Lázaro. Las cadenas de hierro que laceraron sus tobillos de adolescente y el polvo abrasador no doblegaron su espíritu; por el contrario, grabaron en su alma un compromiso inextinguible con la libertad que orientaría cada página de su fecunda existencia.",
    "Conmutada su pena por el destierro en España, Martí obtuvo títulos en Derecho, Filosofía y Letras en las universidades de Madrid y Zaragoza antes de emprender un periplo apasionado por México, Guatemala y Venezuela, periplo que le permitió palpar directamente los dolores, contradicciones y esperanzas de las jóvenes repúblicas hispanoamericanas. Al comprobar que muchas naciones liberadas habían caído en manos de tiranías caudillistas o élites oligárquicas que imitaban con servilismo modelos foráneos, Martí maduró su doctrina sobre la descolonización cultural y la soberanía continental. En enero de 1891 publicó su ensayo fundamental, 'Nuestra América', texto profético donde advirtió con deslumbrante clarividencia que 'el gobierno ha de nacer del país' y que 'trincheras de ideas valen más que trincheras de piedra'.",
    "Instalado durante casi quince años en Nueva York como corresponsal de prestigiosos periódicos continentales, Martí admiró el dinamismo cívico de los Estados Unidos, pero detectó con alarma el surgimiento de apetitos imperialistas que amenazaban la soberanía de las Antillas. Consciente de que si Cuba caía bajo la órbita de Washington el equilibrio continental se quebraría en perjuicio de los pueblos del sur, Martí se consagró a preparar la que denominó la 'guerra necesaria': una contienda bélica sin odio hacia el español honrado, rápida en su ejecución y generosa en sus fines, orientada a fundar una república democrática 'con todos y para el bien de todos'.",
    "El genio político de Martí brilló de manera insuperable al lograr la reconciliación entre los veteranos legendarios de la primera gesta —figuras militares de la talla de Máximo Gómez y Antonio Maceo— y las nuevas generaciones de jóvenes que no habían combatido en la manigua. En los talleres de tabaco de Tampa y Cayo Hueso en Florida, Martí encontró su base social más leal y abnegada: los torcedores cubanos emigrados que escuchaban sus discursos electrizantes entre el aroma a hoja curada y donaban un día de salario por semana para comprar armas y pertrechos. Con ellos fundó en 1892 el Partido Revolucionario Cubano, la primera organización política moderna concebida como un instrumento unitario y democrático para conquistar la emancipación de Cuba y auxiliar a la de Puerto Rico.",
    "Tras superar dolorosos reveses, como la incautación en el puerto de Fernandina de tres barcos de armamento que la conspiración había reunido con indecible sacrificio, Martí firmó junto al general Gómez el 'Manifiesto de Montecristi' y zarpó en una frágil goleta para desembarcar en Playitas de Cajobabo la noche del 11 de abril de 1895. El poeta marchó a pie entre ciénagas y peñascos bajo el aguacero tropical con un revólver al cinto y una cartera repleta de notas manuscritas, sintiendo el orgullo indecible de respirar por fin el aire libre de su tierra amada.",
    "Su destino fatal se selló apenas cinco semanas después, el mediodía del 19 de mayo de 1895 en los campos de Dos Ríos. Al estallar un tiroteo imprevisto con una columna realista, Gómez ordenó a Martí permanecer en la retaguardia para salvaguardar la vida del líder civil supremo. Sin embargo, llevado por un impulso ético irresistible de congruencia heroica entre la palabra predicada y el sacrificio personal, el Apóstol espoleó su caballo blanco y cabalgó solo hacia las líneas enemigas, cayendo abatido por tres disparos de fusil entre la hierba alta y la sombra de los algarrobos.",
    "La caída de José Martí privó a la revolución cubana de su mente más lúcida y humanista en vísperas de la victoria contra el colonialismo español y de la posterior intervención militar estadounidense de 1898. No obstante, su legado poético, sus 'Versos sencillos' y su intransigente ética antimperialista sobrevivieron a su muerte física, convirtiéndose en el faro inextinguible que ha nutrido la conciencia moral de cada generación de cubanos, recordándoles que la única soberanía auténtica descansa sobre el cultivo de la virtud, la justicia distributiva y la fraternidad de los humildes."
]

cuba_03_paras = [
    "La madrugada del 1 de enero de 1959 transformó de manera irreversible el destino de Cuba y la correlación de fuerzas políticas en todo el hemisferio occidental. Ante el colapso inminente de sus líneas militares y el avance implacable de las columnas guerrilleras comandadas por Ernesto 'Che' Guevara y Camilo Cienfuegos tras la batalla decisiva de Santa Clara, el dictador Fulgencio Batista huyó secretamente en un avión militar hacia la República Dominicana, cargando millones de dólares del erario público. En La Habana y Santiago de Cuba, multitudes jubilosas se volcaron a las calles para celebrar la caída de un régimen despótico que durante siete años había clausurado las libertades constitucionales, ensangrentado las ciudades con torturas policiales y convertido la economía nacional en un paraíso especulativo para casinos y corporaciones extranjeras.",
    "La entrada triunfal de la 'Caravana de la Libertad' encabezada por Fidel Castro a La Habana el 8 de enero concitó el entusiasmo fervoroso de millones de ciudadanos que anhelaban la restauración de la democracia y la justicia social. Sin embargo, el rumbo del proceso se radicalizó con una celeridad vertiginosa: en mayo de 1959 se promulgó la Primera Ley de Reforma Agraria, que proscribió el latifundio, limitó la posesión de la tierra a cuatrocientas hectáreas y distribuyó títulos de propiedad a más de cien mil campesinos arrendatarios que vivían en condiciones precarias. Cuando las compañías estadounidenses que controlaban el sector azucarero, los teléfonos y las refinerías de petróleo se opusieron a las compensaciones ofrecidas, el gobierno procedió a su nacionalización masiva, precipitando la ruptura diplomática con Washington en enero de 1961.",
    "En medio de esta confrontación geopolítica creciente, Cuba emprendió la que la UNESCO calificaría posteriormente como una de las gestas pedagógicas más extraordinarias del siglo XX: la Campaña Nacional de Alfabetización de 1961. En una isla donde casi un millón de personas —más del veintitrés por ciento de la población adulta, concentrada principalmente en el campo— no sabía leer ni escribir, el gobierno movilizó a más de doscientos cincuenta mil educadores voluntarios. Entre ellos destacaron cien mil adolescentes y jóvenes de secundaria, conocidos como los brigadistas 'Conrado Benítez', quienes empacaron en sus mochilas un farol de queroseno, la cartilla de lectura 'Venceremos' y un par de mudas de ropa para marchar hacia los rincones más inaccesibles de la Sierra Maestra y los llanos del Camagüey.",
    "Durante meses inolvidables, aquellos jóvenes citadinos compartieron la choza de tierra apisonada de los campesinos, labraron los sembradíos durante el día y enseñaron las primeras letras a la luz temblorosa del farol por las noches, enseñando a firmar por primera vez a ancianos cuyas manos encallecidas jamás habían sujetado un lápiz. A pesar de los ataques de bandas armadas opositoras en las montañas que costaron la vida a varios maestros voluntarios, la campaña culminó el 22 de diciembre de 1961 en la plaza de la Revolución con un saldo apabullante: más de setecientas mil personas fueron alfabetizadas, reduciendo el analfabetismo al 3.9 por ciento y declarando a Cuba territorio libre de analfabetismo.",
    "La radicalización del modelo cubano y su proclamación como revolución socialista en vísperas del desembarco armado de Bahía de Cochinos (Playa Girón) en abril de 1961 —donde las milicias populares derrotaron a una brigada invasora financiada por la CIA en apenas sesenta y seis horas— sellaron la alianza estratégica de La Habana con la Unión Soviética. El punto culminante de esta confrontación se produjo en octubre de 1962 durante la 'Crisis de los Misiles'. El descubrimiento por parte de aviones espías estadounidenses de rampas nucleares soviéticas instaladas en suelo cubano desató un bloqueo naval de Washington y colocó al planeta al borde de una catástrofe atómica mundial durante trece días de angustia extrema.",
    "El acuerdo final alcanzado directamente entre John F. Kennedy y Nikita Jrushchov a espaldas del liderazgo cubano —mediante el cual Moscú retiró los misiles a cambio del compromiso estadounidense de no invadir la isla y de retirar sus propios cohetes en Turquía— causó una profunda indignación en La Habana, revelando la vulnerabilidad de las pequeñas naciones atrapadas en las componendas de las superpotencias. A partir de entonces, Washington endureció el embargo comercial, financiero y marítimo que perdura hasta el presente, mientras Cuba reconstruía sus estructuras bajo la tutela técnica y el subsidio petrolero del bloque socialista europeo.",
    "A más de seis décadas de aquellos acontecimientos sísmicos, el año 1959 sigue constituyendo la gran encrucijada de la historia contemporánea de Cuba. Si bien la revolución erradicó el analfabetismo, universalizó el acceso a la salud pública y forjó una soberanía internacional que desafió al mayor imperio del planeta, el régimen resultante instauró un monopolio político unipartidista y una centralización económica que limitarían severamente las libertades individuales y la prosperidad productiva, dejando abierta una compleja dialéctica entre conquistas sociales indiscutibles y contradicciones institucionales irresueltas."
]

cuba_05_paras = [
    "La desintegración formal de la Unión Soviética en diciembre de 1991 asestó a la sociedad cubana el golpe económico y existencial más devastador de su historia contemporánea. En cuestión de meses, la isla caribeña perdió de manera fulminante el ochenta y cinco por ciento de su comercio exterior, los créditos subsidiados y el suministro vital de trece millones de toneladas anuales de petróleo soviético que alimentaban sus centrales termoeléctricas y fábricas. El producto interno bruto se desplomó un treinta y cinco por ciento entre 1989 y 1993, inaugurando una etapa de penuria extrema bautizada oficialmente como el 'Período Especial en tiempo de paz', un cataclismo material que obligó a once millones de ciudadanos a librar una titánica batalla diaria por la mera subsistencia.",
    "La vida cotidiana en las ciudades y campos cubanos durante los primeros años noventa se convirtió en una pesadilla de privaciones materiales. Los 'apagones' eléctricos de dieciséis horas diarias paralizaban los hogares en medio del calor asfixiante del verano antillano, el transporte público colapsó hasta el punto de que La Habana se inundó de medio millón de bicicletas chinas importadas de urgencia, y la tradicional 'libreta de abastecimiento' racionada vio reducirse sus cuotas a cantidades mínimas de arroz, frijoles y azúcar. Ante la escasez casi total de combustible y fertilizantes químicos, la agricultura debió reinventarse mediante la tracción animal con bueyes y la creación pionera de 'organopónicos' y huertos urbanos comunitarios en solares abandonados, modelo agroecológico que la comunidad científica elogió como un hito de sostenibilidad forzada.",
    "Para evitar el colapso definitivo del Estado, el gobierno implementó a partir de 1993 una serie de reformas heterodoxas que alteraron profundamente el pacto social igualitario. Se despenalizó la tenencia de divisas extranjeras, se autorizó la inversión foránea en complejos hoteleros bajo empresas mixtas, se abrieron mercados agropecuarios libres y se autorizó el 'cuentapropismo' o trabajo privado en diversos oficios artesanales y gastronómicos. La apertura al turismo inyectó los dólares necesarios para sostener los servicios públicos universales de salud y educación; sin embargo, engendró una marcada 'dualidad económica' donde quienes recibían propinas en hoteles o remesas familiares disfrutaban de un poder adquisitivo infinitamente superior al de médicos y maestros que cobraban modestos salarios en pesos cubanos.",
    "Esta profunda fractura socioeconómica y la desesperanza juvenil alimentaron sucesivas olas migratorias de dramatismo sobrecogedor. En el caluroso verano de 1994, tras las protestas callejeras conocidas como el 'Maleconazo', más de treinta y cinco mil cubanos se lanzaron al estrecho de la Florida en frágiles balsas caseras construidas con cámaras de camión y maderas en la célebre 'Crisis de los Balseros'. La tragedia marítima forzó a las administraciones de Clinton y Castro a firmar nuevos acuerdos migratorios para canalizar un éxodo legal mediante una cuota mínima de veinte mil visas anuales, estableciendo la controvertida política de 'pies secos, pies mojados'.",
    "El breve deshielo diplomático iniciado en diciembre de 2014 por los presidentes Barack Obama y Raúl Castro —simbolizado por la reapertura de embajadas, la histórica visita presidencial estadounidense a La Habana en 2016 y la llegada de cruceros y vuelos comerciales directos— desató una ola de esperanza entre los emprendedores locales que abrieron restaurantes privados ('paladares') y hospedajes. Sin embargo, aquel florecimiento resultó efímero: el posterior endurecimiento del embargo bajo la administración Trump con más de doscientas cuarenta nuevas sanciones y el impacto devastador de la pandemia mundial de COVID-19 en 2020 volvieron a estrangular la maltrecha economía insular.",
    "A partir de 2021, la implementación de una traumática reforma monetaria destinada a unificar las dos monedas desencadenó una severa inflación que pulverizó los salarios estatales. La escasez de medicamentos esenciales, el desabastecimiento crónico de alimentos y los apagones provocaron las históricas manifestaciones populares del 11 de julio de 2021 (el '11J'), las más extendidas en seis décadas. La respuesta oficial combinó el endurecimiento penal de las protestas con una flexibilización económica que permitió la creación formal de pequeñas y medianas empresas privadas (mipymes), abriendo un mercado dual donde conviven estantes con artículos importados a precios prohibitivos con largas filas en las bodegas estatales.",
    "El resultado inmediato de esta combinación de asfixia material y desesperanza ha sido el mayor éxodo migratorio en la historia de la nación: entre 2022 y 2024, más de medio millón de cubanos —casi el cinco por ciento de la población total, concentrada en sus estratos más jóvenes y calificados— abandonaron la isla por vía aérea o a través de extenuantes rutas centroamericanas hacia la frontera de los Estados Unidos. Así, la Cuba contemporánea se debate en una encrucijada existencial inaplazable: preservar las conquistas de soberanía y justicia social que enorgullecieron a su pueblo, o reinventar con urgencia sus estructuras productivas y políticas para ofrecer un horizonte digno a una ciudadanía cuya capacidad de resistencia parece haber alcanzado su límite histórico."
]

cuba_capstone_paras = [
    "Comprender a Cuba exige desprenderse de esquemas binarios reductores y adentrarse en uno de los territorios culturales y geopolíticos más paradójicos y apasionantes de la historia moderna. Suspendida en el centro del mar de las Antillas como una 'caimán verde' de más de mil doscientos kilómetros de longitud, esta isla mayor del Caribe ha ejercido sobre el imaginario universal una fascinación magnética que desborda con creces su extensión territorial. Desde las fortificaciones renacentistas de La Habana hasta los mogotes jurásicos de Viñales, desde los versos encendidos de José Martí hasta las síncopas irresistibles del son tradicional, Cuba representa un crisol donde la grandeza estética, la tragedia política y la tenacidad cotidiana se entrelazan de modo indisoluble.",
    "El primer pilar de esta singularidad radica en su condición histórica de frontera oceánica y encrucijada imperial. Al erigirse durante tres centurias en el puerto de escala obligado para las flotas del Imperio español que conectaban los tesoros virreinales con Europa, La Habana forjó una vocación cosmopolita prematura. Su arquitectura barroca y neoclásica de piedra caliza fosilífera, atesorada en las plazas de Armas, de la Catedral y de San Francisco, coexiste con el eclecticismo de sus casonas de El Vedado y el Art Déco del Edificio Bacardí, testimoniando una prosperidad urbana que supo dialogar con las corrientes estéticas del orbe mientras resguardaba patios umbríos donde el agua de los aljibes apaciguaba el bochorno tropical.",
    "Paralelamente, la campiña cubana configuró un orden cultural en torno al tabaco y la caña de azúcar, dualidad inmortalizada magistralmente por Fernando Ortiz en su clásico 'Contrapunteo cubano del tabaco y el azúcar'. Mientras el ingenio azucarero colonial dependió de la mano de obra esclavizada africana sometida a una disciplina brutal en barracones para alimentar el mercado especulativo, la 'vega' de tabaco fomentó el minifundio familiar, el apego amoroso a la tierra de Pinar del Río y el trabajo artesanal meticuloso. En ese fértil mestizaje, los cantos sagrados de los cabildos yorubas y las décimas hispánicas alumbraron una religiosidad sincrética —la santería— y una sensibilidad acústica donde la rumba y el son rompieron todas las barreras sociales.",
    "En el terreno político, la isla forjó su vocación de soberanía a través de tres décadas de guerras anticoloniales contra España (1868-1898). La figura gigantesca de José Martí iluminó ese combate al concebir una república cívica sintetizada en su fórmula 'con todos y para el bien de todos'. Su ensayo 'Nuestra América' anticipó con clarividencia las asechanzas del imperialismo emergente, fundando una tradición de dignidad intelectual que sobreviviría a su trágica muerte en el combate de Dos Ríos y a la tutela impuesta por Washington mediante la Enmienda Platt tras la intervención estadounidense de 1898.",
    "Esa búsqueda incesante de autodeterminación eclosionó con fuerza telúrica en la Revolución de 1959 encabezada por Fidel Castro. El desmantelamiento de la dictadura de Batista, la reforma agraria y la colosal Campaña Nacional de Alfabetización de 1961 —que redujo el analfabetismo al 3.9 por ciento en un solo año— consagraron la revolución ante los pueblos del Tercer Mundo. Sin embargo, la confrontación existencial con Washington durante la Guerra Fría, simbolizada por Playa Girón y la Crisis de los Misiles de 1962, condujo a una alianza con el bloque soviético y a la instauración de un monopolio estatal que limitaría las libertades cívicas y pluralistas.",
    "El derrumbe de la Unión Soviética en 1991 desató la dura prueba del Período Especial, obligando a los cubanos a desplegar una creatividad heroica para sobrevivir a apagones interminables y escasez de alimentos. La apertura al turismo, la despenalización del dólar y las licencias para empresas privadas (mipymes) aliviaron las arcas fiscales, pero profundizaron una desigualdad monetaria que contrasta con el idealismo de antaño. En este contexto de carestías materiales y cerco económico foráneo, el país ha presenciado en los últimos años el mayor éxodo migratorio de su historia, dispersando a cientos de miles de jóvenes por el mundo.",
    "Con todo, el enigma cubano no reside en sus fracturas materiales, sino en la milagrosa permanencia de su espíritu vital. En medio de cualquier tormenta, La Habana sigue vibrando al compás de sus trovadores, la melodía de Compay Segundo y Silvio Rodríguez acompaña las esperanzas íntimas de las familias, y los cineastas continúan escudriñando con lucidez las encrucijadas de su tiempo. Cuba perdura así en la conciencia universal como un testimonio indeleble de que la dignidad soberana, el amor por la palabra poética y la alegría indomable de la música son fuerzas humanas invencibles, capaces de sobrevolar las penurias del presente."
]

stories_to_write = [
    ("stories/world/b2/b2-cuba-01.json", cuba_01_paras),
    ("stories/world/b2/b2-cuba-02.json", cuba_02_paras),
    ("stories/world/b2/b2-cuba-03.json", cuba_03_paras),
    ("stories/world/b2/b2-cuba-05.json", cuba_05_paras),
    ("stories/world/b2/b2-cuba-consolidation.json", cuba_capstone_paras),
    ("stories/world/b2/b2-cuba.json", cuba_capstone_paras)
]

for rel_path, paras in stories_to_write:
    file_path = BASE / rel_path
    with open(file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    data["paragraphs"] = [{"type": "narration", "text": p} for p in paras]
    total_words = sum(len(p.split()) for p in paras)
    print(f"{file_path.name:30s}: {total_words:4d} words (650-825)")
    assert 650 <= total_words <= 825, f"Word count out of range: {total_words}"
    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

print("\nAll calibrated stories successfully written to content/es-latam/!")
